"use client"
import Link from "next/link"
import {useMemo,useState} from "react"
import {Eye,Plus,Search} from "lucide-react"
import {DocumentForm} from "@/components/dashboard/document-form"
import {Header} from "@/components/dashboard/header"
import {Badge} from "@/components/ui/badge"
import {Button} from "@/components/ui/button"
import {Card,CardContent} from "@/components/ui/card"
import {Input} from "@/components/ui/input"
import {Select,SelectContent,SelectItem,SelectTrigger,SelectValue} from "@/components/ui/select"
import {Sheet,SheetContent,SheetDescription,SheetHeader,SheetTitle} from "@/components/ui/sheet"
import {Table,TableBody,TableCell,TableHead,TableHeader,TableRow} from "@/components/ui/table"
import {Tooltip,TooltipContent,TooltipProvider,TooltipTrigger} from "@/components/ui/tooltip"
import type {DocumentRecord,DocumentReferences} from "@/lib/documents/types"
type Item=DocumentRecord&{typeLabel:string;linkedLabel:string}
const PAGE_SIZE=10
const formatSize=(value:string)=>{const bytes=Number(value);if(!Number.isFinite(bytes)||bytes<=0)return"Non renseigné";return bytes>=1024*1024?`${(bytes/1024/1024).toFixed(1)} Mo`:`${Math.ceil(bytes/1024)} Ko`}
export default function DocumentsClient({items,references,canEdit,initialCreate=false}:{items:Item[];references:DocumentReferences;canEdit:boolean;initialCreate?:boolean}){
 const[query,setQuery]=useState(""),[typeFilter,setTypeFilter]=useState("TOUS"),[entityTypeFilter,setEntityTypeFilter]=useState("TOUS"),[page,setPage]=useState(1),[createOpen,setCreateOpen]=useState(initialCreate)
 const filtered=useMemo(()=>{const search=query.trim().toLocaleLowerCase("fr");return items.filter((item)=>(!search||[item.id_document,item.nom_document,item.typeLabel,item.note,item.type_entite_liee,item.linkedLabel].join(" ").toLocaleLowerCase("fr").includes(search))&&(typeFilter==="TOUS"||item.id_type_document===typeFilter)&&(entityTypeFilter==="TOUS"||item.type_entite_liee===entityTypeFilter))},[items,query,typeFilter,entityTypeFilter])
 const pageCount=Math.max(1,Math.ceil(filtered.length/PAGE_SIZE)),currentPage=Math.min(page,pageCount),visible=filtered.slice((currentPage-1)*PAGE_SIZE,currentPage*PAGE_SIZE),storage=items.reduce((sum,item)=>sum+(Number(item.taille)||0),0),linked=items.filter((item)=>item.type_entite_liee&&item.id_entite_liee).length
 const documentTypes=references.hasDocumentTypeReferential?references.documentTypes:[...new Map(items.filter((item)=>item.id_type_document).map((item)=>[item.id_type_document,{id:item.id_type_document,label:item.typeLabel}])).values()]
 const filter=(setter:(value:string)=>void,value:string)=>{setter(value);setPage(1)}
 const detail=(item:Item)=><TooltipProvider><Tooltip><TooltipTrigger asChild><Button asChild variant="ghost" size="icon"><Link href={`/dashboard/documents/${item.id_document}`} aria-label={`Voir les détails de ${item.nom_document}`}><Eye className="h-4 w-4"/></Link></Button></TooltipTrigger><TooltipContent>Voir les détails</TooltipContent></Tooltip></TooltipProvider>
 return <div className="min-h-screen min-w-0 overflow-x-hidden"><Header title="Documents" subtitle="Référentiel documentaire"/><main className="min-w-0 space-y-6 p-4 sm:p-6">
  <div className="flex justify-end">{canEdit&&<Button onClick={()=>setCreateOpen(true)}><Plus className="h-4 w-4"/>Nouveau document</Button>}</div>
  <div className="grid gap-3 sm:grid-cols-2 xl:grid-cols-4">{[["Total documents",items.length],["Documents liés",linked],["Documents non liés",items.length-linked],["Stockage",formatSize(String(storage))]].map(([label,value])=><Card key={label}><CardContent className="p-4"><p className="text-2xl font-semibold tabular-nums">{value}</p><p className="text-sm text-muted-foreground">{label}</p></CardContent></Card>)}</div>
  <div className="flex min-w-0 flex-col gap-3 lg:flex-row"><div className="relative min-w-0 flex-1 lg:max-w-md"><Search className="absolute left-3 top-3 h-4 w-4 text-muted-foreground"/><Input className="pl-9" aria-label="Rechercher un document" placeholder="Rechercher un document…" value={query} onChange={(e)=>filter(setQuery,e.target.value)}/></div><Select value={typeFilter} onValueChange={(v)=>filter(setTypeFilter,v)}><SelectTrigger className="w-full lg:w-52" aria-label="Filtrer par type"><SelectValue/></SelectTrigger><SelectContent><SelectItem value="TOUS">Tous les types</SelectItem>{documentTypes.map((type)=><SelectItem key={type.id} value={type.id}>{type.label}</SelectItem>)}</SelectContent></Select><Select value={entityTypeFilter} onValueChange={(v)=>filter(setEntityTypeFilter,v)}><SelectTrigger className="w-full lg:w-52" aria-label="Filtrer par rattachement"><SelectValue/></SelectTrigger><SelectContent><SelectItem value="TOUS">Tous les rattachements</SelectItem>{references.entityTypes.map((type)=><SelectItem key={type.id} value={type.id}>{type.label}</SelectItem>)}</SelectContent></Select></div>
  <Card className="min-w-0 overflow-hidden"><CardContent className="p-0"><div className="hidden lg:block"><Table><TableHeader><TableRow><TableHead>ID</TableHead><TableHead>Document</TableHead><TableHead>Type</TableHead><TableHead>Rattachement</TableHead><TableHead>Taille</TableHead><TableHead>Fichier</TableHead><TableHead/></TableRow></TableHeader><TableBody>{visible.map((item)=><TableRow key={item.id_document}><TableCell className="font-mono text-xs">{item.id_document}</TableCell><TableCell className="max-w-72 whitespace-normal font-medium">{item.nom_document}</TableCell><TableCell>{item.typeLabel||"Non renseigné"}</TableCell><TableCell className="max-w-72 whitespace-normal">{item.type_entite_liee?`${item.type_entite_liee} · ${item.linkedLabel||item.id_entite_liee}`:"Non renseigné"}</TableCell><TableCell>{formatSize(item.taille)}</TableCell><TableCell><Badge variant={item.drive_document_id?"secondary":"outline"}>{item.drive_document_id?"Disponible":"Non disponible"}</Badge></TableCell><TableCell>{detail(item)}</TableCell></TableRow>)}{!visible.length&&<TableRow><TableCell colSpan={7} className="h-24 text-center text-muted-foreground">Aucun document trouvé.</TableCell></TableRow>}</TableBody></Table></div>
   <div className="grid min-w-0 gap-3 p-3 sm:grid-cols-2 lg:hidden">{visible.map((item)=><article key={item.id_document} className="min-w-0 rounded-lg border p-4"><div className="flex items-start justify-between gap-3"><div className="min-w-0"><p className="break-words font-medium">{item.nom_document||"Non renseigné"}</p><p className="break-all font-mono text-xs text-muted-foreground">{item.id_document}</p></div>{detail(item)}</div><div className="mt-3 space-y-2 text-sm"><p>{item.typeLabel||"Non renseigné"}</p><p className="break-words text-muted-foreground">{item.linkedLabel||"Non renseigné"}</p><div className="flex items-center justify-between gap-2"><span>{formatSize(item.taille)}</span><Badge variant={item.drive_document_id?"secondary":"outline"}>{item.drive_document_id?"Disponible":"Non disponible"}</Badge></div></div></article>)}{!visible.length&&<p className="py-10 text-center text-sm text-muted-foreground sm:col-span-2">Aucun document trouvé.</p>}</div>
  </CardContent></Card>
  {pageCount>1&&<div className="flex items-center justify-between gap-3 text-sm text-muted-foreground"><span>Page {currentPage} sur {pageCount} · {filtered.length} document(s)</span><div className="flex gap-2"><Button variant="outline" size="sm" disabled={currentPage===1} onClick={()=>setPage(currentPage-1)}>Précédent</Button><Button variant="outline" size="sm" disabled={currentPage===pageCount} onClick={()=>setPage(currentPage+1)}>Suivant</Button></div></div>}
 </main><Sheet open={createOpen} onOpenChange={setCreateOpen}><SheetContent className="w-full overflow-y-auto sm:max-w-2xl"><SheetHeader><SheetTitle>Nouveau document</SheetTitle><SheetDescription>Créer une fiche documentaire et joindre éventuellement un PDF.</SheetDescription></SheetHeader><div className="px-4"><DocumentForm references={references}/></div></SheetContent></Sheet></div>
}
