export const COMPETITION_HEADERS = ["id_competition", "nom_competition", "id_type_competition", "edition", "est_multisport", "niveau_competition", "date_debut", "date_fin", "pays", "ville", "lieu", "statut", "observations"] as const
export const TEAM_PARTICIPATION_HEADERS = ["id_participation_equipe", "id_competition", "id_equipe_nationale", "statut_participation", "date_engagement", "observations"] as const
export const PROGRAM_HEADERS = ["id_programme_competition", "id_competition", "id_epreuve", "id_categorie_age", "id_sexe", "date_debut", "date_fin", "observations"] as const

export type CompetitionStatus = "PLANIFIEE" | "A_VENIR" | "EN_COURS" | "TERMINEE" | "REPORTEE" | "ANNULEE" | "NON_RENSEIGNE"
export type Competition = Record<(typeof COMPETITION_HEADERS)[number], string> & { statut_normalise: CompetitionStatus }
export type TeamParticipation = Record<(typeof TEAM_PARTICIPATION_HEADERS)[number], string>
export type CompetitionProgram = Record<(typeof PROGRAM_HEADERS)[number], string>
export type CampaignEngagement = { id_engagement_campagne: string; id_programme_competition: string; id_campagne: string; id_statut_engagement: string; date_engagement: string; date_debut: string; date_fin: string; id_federation_source: string; date_transmission: string; reference_source: string; observation: string; id_equipe_nationale?: string; nom_equipe_nationale?: string; nom_campagne?: string; id_federation_responsable?: string }
export type AthleteParticipation = { id_participation_athlete:string; id_engagement_campagne:string; id_selection:string; id_statut_participation:string; date_statut:string; id_selection_remplacement:string; observation:string; athlete_id?:string; athlete_label?:string; campaign_id?:string }
export type CompetitionResult = { id_resultat:string;id_resultat_logique:string;numero_version:string;id_resultat_precedent:string;est_version_courante:string;id_engagement_campagne:string;id_programme_competition:string;date_resultat:string;phase:string;adversaire:string;pays_adversaire:string;id_resultat_synthetique:string;valeur_rdc:string;valeur_adversaire:string;id_unite_mesure:string;id_decision_resultat:string;id_federation_source:string;date_transmission:string;reference_source:string;id_statut_validation_resultat:string;date_validation:string;id_validateur_coc:string;motif_correction:string;observation:string;nom_equipe_nationale?:string;nom_campagne?:string }
export type ResultSegment={id_segment_resultat:string;id_resultat:string;id_type_segment:string;numero_segment:string;valeur_rdc:string;valeur_adversaire:string;observation:string}
export type IndividualPerformance={id_performance:string;id_resultat:string;id_participation_athlete:string;id_type_resultat:string;valeur:string;id_unite_mesure:string;rang:string;est_record:string;est_meilleure_performance:string;id_distinction:string;observation:string;athlete_id?:string;athlete_label?:string;id_federation_source?:string;reference_source?:string}
export type CompetitionOption = { id: string; label: string; parentId?: string; secondary?: string; scope?: string; federationId?: string; sportId?: string; disciplineId?: string; formatId?: string; resultTypeId?: string }
export type NationalTeamOption = { id: string; label: string; federationId: string; federation: string; sportId: string; sport: string; discipline: string }
export type CompetitionReferences = { types: CompetitionOption[]; levels?: CompetitionOption[]; statuses?: CompetitionOption[]; events?: CompetitionOption[]; ageCategories?: CompetitionOption[]; sexes?: CompetitionOption[]; teams: NationalTeamOption[]; teamsAvailable: boolean }
