export const COMPETITION_HEADERS = ["id_competition", "nom_competition", "id_type_competition", "edition", "est_multisport", "niveau_competition", "date_debut", "date_fin", "pays", "ville", "lieu", "statut", "observations"] as const
export const TEAM_PARTICIPATION_HEADERS = ["id_participation_equipe", "id_competition", "id_equipe_nationale", "statut_participation", "date_engagement", "observations"] as const
export const PROGRAM_HEADERS = ["id_programme_competition", "id_competition", "id_epreuve", "id_categorie_age", "id_sexe", "date_debut", "date_fin", "observations"] as const

export type CompetitionStatus = "PLANIFIEE" | "A_VENIR" | "EN_COURS" | "TERMINEE" | "REPORTEE" | "ANNULEE" | "NON_RENSEIGNE"
export type Competition = Record<(typeof COMPETITION_HEADERS)[number], string> & { statut_normalise: CompetitionStatus }
export type TeamParticipation = Record<(typeof TEAM_PARTICIPATION_HEADERS)[number], string>
export type CompetitionProgram = Record<(typeof PROGRAM_HEADERS)[number], string>
export type CampaignEngagement = { id_engagement_campagne: string; id_programme_competition: string; id_campagne: string; id_statut_engagement: string; date_engagement: string; date_debut: string; date_fin: string; id_federation_source: string; date_transmission: string; reference_source: string; observation: string; id_equipe_nationale?: string; nom_equipe_nationale?: string; nom_campagne?: string; id_federation_responsable?: string }
export type AthleteParticipation = { id_participation_acteur:string; id_participation_athlete:string; id_engagement_campagne:string; id_acteur_coc:string; id_type_acteur:string; id_selection:string; id_affectation_staff:string; id_statut_participation:string; date_statut:string; id_participation_remplacement:string; id_selection_remplacement:string; observation:string; athlete_id?:string; athlete_label?:string; actor_label?:string; campaign_id?:string }
export type ParticipatingUnit = { id_unite_participante:string;id_engagement_campagne:string;type_unite:"INDIVIDUEL"|"EQUIPE";id_participation_acteur:string;nom_unite:string;observation:string;composition?:string[];membres?:string[] }
export type CompetitionResult = { id_resultat:string;id_resultat_logique:string;numero_version:string;id_resultat_precedent:string;est_version_courante:string;id_engagement_campagne:string;id_programme_competition:string;id_unite_participante:string;id_discipline?:string;date_resultat:string;phase:string;type_adversaire:string;nom_adversaire:string;adversaire:string;pays_adversaire:string;organisation_adversaire:string;id_resultat_synthetique:string;valeur_coc:string;valeur_rdc:string;valeur_adversaire:string;id_unite_mesure:string;id_decision_resultat:string;id_statut_resultat:string;id_statut_validation_resultat:string;motif_correction:string;observation:string;id_federation_source?:string;date_transmission?:string;reference_source?:string;nom_equipe_nationale?:string;nom_campagne?:string }
export type CompetitionMedal = { id_medaille:string;id_resultat_logique:string;id_distinction:"DIST_OR"|"DIST_ARGENT"|"DIST_BRONZE";date_obtention:string;observation:string;id_unite_participante:string;unit_label:string;event_label:string }
export type CompetitionOption = { id: string; label: string; parentId?: string; secondary?: string; scope?: string; federationId?: string; sportId?: string; disciplineId?: string; formatId?: string; resultTypeId?: string }
export type NationalTeamOption = { id: string; label: string; federationId: string; federation: string; sportId: string; sport: string; discipline: string }
export type CompetitionReferences = { types: CompetitionOption[]; levels?: CompetitionOption[]; statuses?: CompetitionOption[]; events?: CompetitionOption[]; ageCategories?: CompetitionOption[]; sexes?: CompetitionOption[]; sports?: CompetitionOption[]; disciplines?: CompetitionOption[]; federations?: CompetitionOption[]; teams: NationalTeamOption[]; teamsAvailable: boolean }
