"use client"

import Link from "next/link"
import { useRouter } from "next/navigation"
import { useState } from "react"
import { ArrowLeft, Pencil, Plus, Trash2 } from "lucide-react"
import { toast } from "sonner"
import { Header } from "@/components/dashboard/header"
import { ActorSearchSelect } from "@/components/dashboard/actor-search-select"
import { Badge } from "@/components/ui/badge"
import { Button } from "@/components/ui/button"
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card"
import { Label } from "@/components/ui/label"
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select"
import { Sheet, SheetContent, SheetDescription, SheetFooter, SheetHeader, SheetTitle } from "@/components/ui/sheet"
import { Table, TableBody, TableCell, TableHead, TableHeader, TableRow } from "@/components/ui/table"
import { Textarea } from "@/components/ui/textarea"
import { formatPeriod } from "@/lib/activites/format"
import type { Activity, ActivityEntity, ActivityParticipant, ActivityReferences } from "@/lib/activites/types"
import type { DocumentRecord } from "@/lib/documents/types"
import { ActivityForm, activityStatusLabels, emptyActivityForm } from "../activites-client"

const emptyEntity = { id_entite: "", id_role_entite_activite: "", observation: "" }
const emptyParticipant = { id_type_acteur: "", id_acteur_coc: "", id_activite_entite: "", observation: "" }

export default function Detail({ activity, references, initialParticipants, participantsError, initialEntities, entitiesError, actorNames, activityDocuments, canEdit }: { activity: Activity; references: ActivityReferences; initialParticipants: ActivityParticipant[]; participantsError: boolean; initialEntities: ActivityEntity[]; entitiesError: boolean; actorNames: Record<string, string>; activityDocuments?: DocumentRecord[]; canEdit: boolean }) {
  const router = useRouter()
  const [entities, setEntities] = useState(initialEntities)
  const [participants, setParticipants] = useState(initialParticipants)
  const [editOpen, setEditOpen] = useState(false)
  const [entityOpen, setEntityOpen] = useState(false)
  const [participantOpen, setParticipantOpen] = useState(false)
  const [saving, setSaving] = useState(false)
  const [entityEditId, setEntityEditId] = useState("")
  const [participantEditId, setParticipantEditId] = useState("")
  const [form, setForm] = useState({ ...emptyActivityForm, ...Object.fromEntries(Object.keys(emptyActivityForm).map((key) => [key, activity[key as keyof Activity] || ""])) })
  const [eform, setEform] = useState(emptyEntity)
  const [pform, setPform] = useState(emptyParticipant)
  const [actors, setActors] = useState<{ id: string; label: string }[]>([])
  const [displayActorNames, setDisplayActorNames] = useState(actorNames)
  const [actorsLoading, setActorsLoading] = useState(false)
  const name = (items: ActivityReferences["types"], id: string) => items.find((item) => item.id === id)?.label || "—"
  const alphabetical = (left:string,right:string) => left.localeCompare(right,"fr",{sensitivity:"base"})
  const sortedEntities = [...entities].sort((left,right)=>{const leftOrganizer=left.id_entite===activity.id_entite_organisatrice&&left.id_role_entite_activite==="REA006",rightOrganizer=right.id_entite===activity.id_entite_organisatrice&&right.id_role_entite_activite==="REA006";if(leftOrganizer!==rightOrganizer)return leftOrganizer?-1:1;return alphabetical(name(references.entites,left.id_entite),name(references.entites,right.id_entite))})
  const sortedParticipants = [...participants].sort((left,right)=>alphabetical(displayActorNames[left.id_acteur_coc]||left.id_acteur_coc,displayActorNames[right.id_acteur_coc]||right.id_acteur_coc))
  const relation = (id: string) => entities.find((item) => item.id_activite_entite === id)
  const entityLabel = (id: string) => { const item=relation(id);return item ? `${name(references.entites,item.id_entite)} — ${name(references.entityRoles,item.id_role_entite_activite)}` : "—" }
  const participantCount = (id: string) => participants.filter((item) => item.id_activite_entite === id).length

  async function saveActivity(){if(saving)return;setSaving(true);try{const response=await fetch("/api/activites",{method:"PUT",headers:{"Content-Type":"application/json"},body:JSON.stringify({id:activity.id_activite,row:form})}),result=await response.json();if(!response.ok)throw new Error(result.error);toast.success("Activité modifiée.");setEditOpen(false);router.refresh()}catch(error){toast.error(error instanceof Error?error.message:String(error))}finally{setSaving(false)}}
  function addEntity(){setEntityEditId("");setEform(emptyEntity);setEntityOpen(true)}
  function editEntity(row:ActivityEntity){setEntityEditId(row.id_activite_entite);setEform({id_entite:row.id_entite,id_role_entite_activite:row.id_role_entite_activite,observation:row.observation});setEntityOpen(true)}
  async function saveEntity(){if(saving)return;setSaving(true);try{const response=await fetch(`/api/activites/${activity.id_activite}/entites`,{method:entityEditId?"PUT":"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({id:entityEditId,row:eform})}),result=await response.json();if(!response.ok)throw new Error(result.error);setEntities(current=>entityEditId?current.map(item=>item.id_activite_entite===entityEditId?result.row:item):[...current,result.row]);toast.success(entityEditId?"Rôle de l’entité modifié.":"Entité rattachée.");setEntityOpen(false);router.refresh()}catch(error){toast.error(error instanceof Error?error.message:String(error))}finally{setSaving(false)}}
  async function removeEntity(row:ActivityEntity){if(participantCount(row.id_activite_entite)){toast.error("Cette entité possède encore des participants.");return}if(!window.confirm(`Retirer ${name(references.entites,row.id_entite)} de cette activité ?`))return;setSaving(true);try{const response=await fetch(`/api/activites/${activity.id_activite}/entites`,{method:"DELETE",headers:{"Content-Type":"application/json"},body:JSON.stringify({id:row.id_activite_entite})}),result=await response.json();if(!response.ok)throw new Error(result.error);setEntities(current=>current.filter(item=>item.id_activite_entite!==row.id_activite_entite));toast.success("Entité retirée.");router.refresh()}catch(error){toast.error(error instanceof Error?error.message:String(error))}finally{setSaving(false)}}
  async function loadActors(type:string){setPform(current=>({...current,id_type_acteur:type,id_acteur_coc:""}));setActors([]);setActorsLoading(true);try{const response=await fetch(`/api/activites/${activity.id_activite}/participants?type=${encodeURIComponent(type)}`,{cache:"no-store"}),result=await response.json();if(!response.ok)throw new Error(result.error);setActors(Array.isArray(result.actors)?result.actors:[])}catch(error){toast.error(error instanceof Error?error.message:String(error))}finally{setActorsLoading(false)}}
  function addParticipant(){if(!entities.length){toast.error("Ajoutez d’abord une entité à cette activité.");addEntity();return}setParticipantEditId("");setPform(emptyParticipant);setActors([]);setParticipantOpen(true)}
  function editParticipant(row:ActivityParticipant){setParticipantEditId(row.id_participation);setPform({id_type_acteur:row.id_type_acteur,id_acteur_coc:row.id_acteur_coc,id_activite_entite:row.id_activite_entite,observation:row.observation});setActors([{id:row.id_acteur_coc,label:displayActorNames[row.id_acteur_coc]||row.id_acteur_coc}]);setParticipantOpen(true)}
  async function saveParticipant(){if(saving)return;setSaving(true);try{const response=await fetch(`/api/activites/${activity.id_activite}/participants`,{method:participantEditId?"PUT":"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({id:participantEditId,row:pform})}),result=await response.json();if(!response.ok)throw new Error(result.error);const selectedActor=actors.find(item=>item.id===result.row.id_acteur_coc);if(selectedActor)setDisplayActorNames(current=>({...current,[selectedActor.id]:selectedActor.label}));setParticipants(current=>participantEditId?current.map(item=>item.id_participation===participantEditId?result.row:item):[...current,result.row]);toast.success(participantEditId?"Participant modifié.":"Participant ajouté.");setParticipantOpen(false);router.refresh()}catch(error){toast.error(error instanceof Error?error.message:String(error))}finally{setSaving(false)}}

  return <div className="min-w-0"><Header title={activity.nom_activite} subtitle="Fiche activité" /><main className="min-w-0 space-y-6 p-4 sm:p-6">
    <div className="flex justify-between"><Button asChild variant="ghost"><Link href="/dashboard/activites"><ArrowLeft className="mr-2 h-4 w-4" />Retour</Link></Button>{canEdit&&<Button onClick={()=>setEditOpen(true)}><Pencil className="mr-2 h-4 w-4" />Modifier</Button>}</div>
    <div className="grid gap-5 lg:grid-cols-3"><Card className="lg:col-span-2"><CardHeader><CardTitle>Informations générales</CardTitle></CardHeader><CardContent className="grid gap-4 sm:grid-cols-2">{[["ID",activity.id_activite],["Nom",activity.nom_activite],["Titre public",activity.titre_public],["Type",name(references.types,activity.id_type_activite)],["Entité organisatrice",name(references.entites,activity.id_entite_organisatrice)],["Période",formatPeriod(activity.date_debut,activity.date_fin)],["Localisation",[activity.pays,activity.ville,activity.lieu].filter(Boolean).join(" — ")||"—"]].map(([label,value])=><div key={label}><p className="text-xs text-muted-foreground">{label}</p><p className="font-medium">{value||"—"}</p></div>)}<div><p className="text-xs text-muted-foreground">Statut</p><Badge>{activityStatusLabels[activity.statut_normalise]}</Badge></div></CardContent></Card><Card><CardHeader><CardTitle>Résumé</CardTitle></CardHeader><CardContent className="whitespace-pre-wrap text-sm text-muted-foreground">{activity.resume||"Aucun résumé."}</CardContent></Card></div>
    <Card className="min-w-0 overflow-hidden"><CardHeader className="flex-row items-center justify-between"><CardTitle>Entités</CardTitle>{canEdit&&<Button size="sm" onClick={addEntity}><Plus className="mr-2 h-4 w-4" />Ajouter une entité</Button>}</CardHeader><CardContent className="p-0">{entitiesError?<p className="p-5 text-destructive">Impossible de charger les entités participantes.</p>:<Table><TableHeader><TableRow><TableHead>Entité</TableHead><TableHead>Rôle</TableHead><TableHead>Participants</TableHead>{canEdit&&<TableHead className="w-24">Actions</TableHead>}</TableRow></TableHeader><TableBody>{sortedEntities.map(row=>{const organizer=row.id_entite===activity.id_entite_organisatrice&&row.id_role_entite_activite==="REA006";return <TableRow key={row.id_activite_entite}><TableCell className="max-w-72 whitespace-normal font-medium">{name(references.entites,row.id_entite)}</TableCell><TableCell className="whitespace-normal">{name(references.entityRoles,row.id_role_entite_activite)}</TableCell><TableCell>{participantCount(row.id_activite_entite)}</TableCell>{canEdit&&<TableCell><div className="flex"><Button disabled={organizer} variant="ghost" size="icon" onClick={()=>editEntity(row)} title={organizer?"Rôle défini par l’activité":"Modifier le rôle"} aria-label="Modifier le rôle de l’entité"><Pencil className="h-4 w-4" /></Button><Button disabled={organizer} variant="ghost" size="icon" onClick={()=>removeEntity(row)} title={organizer?"L’organisateur ne peut pas être retiré":"Retirer l’entité"} aria-label="Retirer l’entité"><Trash2 className="h-4 w-4" /></Button></div></TableCell>}</TableRow>})}{!entities.length&&<TableRow><TableCell colSpan={canEdit?4:3} className="h-20 text-center text-muted-foreground">Aucune entité rattachée.</TableCell></TableRow>}</TableBody></Table>}</CardContent></Card>
    <Card className="min-w-0 overflow-hidden"><CardHeader className="flex-row items-center justify-between"><CardTitle>Participants</CardTitle>{canEdit&&<Button size="sm" disabled={!entities.length} onClick={addParticipant}><Plus className="mr-2 h-4 w-4" />Ajouter un participant</Button>}</CardHeader><CardContent className="p-0">{!entities.length&&<div className="border-b p-4 text-sm text-muted-foreground">Ajoutez d’abord une entité à cette activité.{canEdit&&<Button variant="link" onClick={addEntity}>Ajouter une entité</Button>}</div>}{participantsError?<p className="p-5 text-destructive">Impossible de charger les participants.</p>:<Table><TableHeader><TableRow><TableHead>Nom complet</TableHead><TableHead>Type</TableHead><TableHead className="hidden md:table-cell">Entité</TableHead><TableHead className="hidden lg:table-cell">Rôle de l’entité</TableHead>{canEdit&&<TableHead className="w-16">Actions</TableHead>}</TableRow></TableHeader><TableBody>{sortedParticipants.map(row=>{const linked=relation(row.id_activite_entite);return <TableRow key={row.id_participation}><TableCell className="max-w-64 whitespace-normal font-medium">{displayActorNames[row.id_acteur_coc]||row.id_acteur_coc}</TableCell><TableCell>{name(references.actorTypes,row.id_type_acteur)}</TableCell><TableCell className="hidden max-w-64 whitespace-normal md:table-cell">{linked?name(references.entites,linked.id_entite):"—"}</TableCell><TableCell className="hidden whitespace-normal lg:table-cell">{linked?name(references.entityRoles,linked.id_role_entite_activite):"—"}</TableCell>{canEdit&&<TableCell><Button variant="ghost" size="icon" onClick={()=>editParticipant(row)} title="Modifier" aria-label="Modifier le participant"><Pencil className="h-4 w-4" /></Button></TableCell>}</TableRow>})}{!participants.length&&<TableRow><TableCell colSpan={canEdit?5:4} className="h-24 text-center text-muted-foreground">Aucun participant.</TableCell></TableRow>}</TableBody></Table>}</CardContent></Card>
    {activityDocuments&&<Card><CardHeader><CardTitle>Documents</CardTitle></CardHeader><CardContent className="p-0"><Table><TableHeader><TableRow><TableHead>Document</TableHead><TableHead>Type</TableHead><TableHead>Taille</TableHead><TableHead /></TableRow></TableHeader><TableBody>{activityDocuments.map(document=><TableRow key={document.id_document}><TableCell className="font-medium">{document.nom_document}</TableCell><TableCell>{document.id_type_document}</TableCell><TableCell>{document.taille?`${Math.ceil(Number(document.taille)/1024)} Ko`:"—"}</TableCell><TableCell><Button asChild variant="ghost" size="sm"><Link href={`/dashboard/documents/${document.id_document}`}>Voir</Link></Button></TableCell></TableRow>)}{!activityDocuments.length&&<TableRow><TableCell colSpan={4} className="h-20 text-center text-muted-foreground">Aucun document lié.</TableCell></TableRow>}</TableBody></Table></CardContent></Card>}
  </main>
  <Sheet open={editOpen} onOpenChange={setEditOpen}><SheetContent className="w-full overflow-y-auto sm:max-w-2xl"><SheetHeader><SheetTitle>Modifier l’activité</SheetTitle><SheetDescription>L’identifiant reste immuable.</SheetDescription></SheetHeader><ActivityForm form={form} setForm={setForm} refs={references}/><SheetFooter><Button variant="outline" onClick={()=>setEditOpen(false)}>Annuler</Button><Button disabled={saving} onClick={saveActivity}>Enregistrer</Button></SheetFooter></SheetContent></Sheet>
  <Sheet open={entityOpen} onOpenChange={setEntityOpen}><SheetContent className="w-full overflow-y-auto sm:max-w-lg"><SheetHeader><SheetTitle>{entityEditId?"Modifier le rôle":"Ajouter une entité"}</SheetTitle><SheetDescription>Le rôle décrit la place de l’entité dans cette activité.</SheetDescription></SheetHeader><div className="grid gap-4 px-4"><div className="space-y-2"><Label>Entité *</Label><Select disabled={!!entityEditId} value={eform.id_entite} onValueChange={value=>setEform(current=>({...current,id_entite:value}))}><SelectTrigger><SelectValue placeholder="Sélectionner" /></SelectTrigger><SelectContent>{references.entites.map(item=><SelectItem key={item.id} value={item.id}>{item.secondary?`${item.secondary} — `:""}{item.label}</SelectItem>)}</SelectContent></Select></div><div className="space-y-2"><Label>Rôle dans l’activité *</Label><Select value={eform.id_role_entite_activite} onValueChange={value=>setEform(current=>({...current,id_role_entite_activite:value}))}><SelectTrigger><SelectValue placeholder="Sélectionner" /></SelectTrigger><SelectContent>{references.entityRoles.map(item=><SelectItem key={item.id} value={item.id}>{item.label}</SelectItem>)}</SelectContent></Select></div><div className="space-y-2"><Label>Observation</Label><Textarea value={eform.observation} onChange={event=>setEform(current=>({...current,observation:event.target.value}))}/></div></div><SheetFooter><Button variant="outline" onClick={()=>setEntityOpen(false)}>Annuler</Button><Button disabled={saving} onClick={saveEntity}>Enregistrer</Button></SheetFooter></SheetContent></Sheet>
  <Sheet open={participantOpen} onOpenChange={setParticipantOpen}><SheetContent className="w-full overflow-y-auto sm:max-w-lg"><SheetHeader><SheetTitle>{participantEditId?"Modifier le participant":"Ajouter un participant"}</SheetTitle><SheetDescription>Le participant doit appartenir à une entité déjà rattachée.</SheetDescription></SheetHeader><div className="grid gap-4 px-4"><div className="space-y-2"><Label>Type d’acteur *</Label><Select value={pform.id_type_acteur} onValueChange={loadActors}><SelectTrigger><SelectValue placeholder="Sélectionner" /></SelectTrigger><SelectContent>{references.actorTypes.map(type=><SelectItem key={type.id} value={type.id}>{type.label}</SelectItem>)}</SelectContent></Select></div><div className="space-y-2"><Label>Participant *</Label><ActorSearchSelect actors={actors} value={pform.id_acteur_coc} onChange={value=>setPform(current=>({...current,id_acteur_coc:value}))} disabled={!pform.id_type_acteur} loading={actorsLoading}/></div><div className="space-y-2"><Label>Entité d’appartenance *</Label><Select value={pform.id_activite_entite} onValueChange={value=>setPform(current=>({...current,id_activite_entite:value}))}><SelectTrigger><SelectValue placeholder="Sélectionner" /></SelectTrigger><SelectContent>{sortedEntities.map(item=><SelectItem key={item.id_activite_entite} value={item.id_activite_entite}>{entityLabel(item.id_activite_entite)}</SelectItem>)}</SelectContent></Select></div><div className="space-y-2"><Label>Observation</Label><Textarea value={pform.observation} onChange={event=>setPform(current=>({...current,observation:event.target.value}))}/></div></div><SheetFooter><Button variant="outline" onClick={()=>setParticipantOpen(false)}>Annuler</Button><Button disabled={saving} onClick={saveParticipant}>Enregistrer</Button></SheetFooter></SheetContent></Sheet>
  </div>
}
