import { Progress } from "@/components/ui/progress"
import { Table, TableBody, TableCell, TableHead, TableHeader, TableRow } from "@/components/ui/table"
import type { ActorsDashboardStats } from "@/lib/acteurs/dashboard"

const number = new Intl.NumberFormat("fr-FR")

export function ActorsSummarySection({ stats }: { stats: ActorsDashboardStats }) {
  const total = stats.types.reduce((acc, item) => ({ total: acc.total + item.total, hommes: acc.hommes + item.hommes, femmes: acc.femmes + item.femmes, actifs: acc.actifs + item.actifs, inactifs: acc.inactifs + item.inactifs, fiches: acc.fiches + item.fichesCompletes }), { total: 0, hommes: 0, femmes: 0, actifs: 0, inactifs: 0, fiches: 0 })
  const completeness = total.total ? Math.round(stats.types.reduce((sum, item) => sum + item.completude * item.total, 0) / total.total) : 0
  return <section aria-labelledby="actors-title" className="space-y-4"><div><h2 id="actors-title" className="text-lg font-semibold">Acteurs</h2><p className="text-sm text-muted-foreground">Répartition et qualité des fiches enregistrées</p></div><div className="overflow-x-auto rounded-lg border border-border/60"><Table><TableHeader><TableRow className="bg-muted/30 hover:bg-muted/30"><TableHead>Type d’acteur</TableHead><TableHead className="text-right">Total</TableHead><TableHead className="text-right">Hommes</TableHead><TableHead className="text-right">Femmes</TableHead><TableHead className="text-right">Actifs</TableHead><TableHead className="text-right">Inactifs</TableHead><TableHead className="text-right">Fiches complètes</TableHead><TableHead className="min-w-36">Complétude</TableHead></TableRow></TableHeader><TableBody>{stats.types.map((item) => <TableRow key={item.key}><TableCell className="font-medium">{item.label}</TableCell><TableCell className="text-right tabular-nums">{number.format(item.total)}</TableCell><TableCell className="text-right tabular-nums">{number.format(item.hommes)}</TableCell><TableCell className="text-right tabular-nums">{number.format(item.femmes)}</TableCell><TableCell className="text-right tabular-nums">{number.format(item.actifs)}</TableCell><TableCell className="text-right tabular-nums">{number.format(item.inactifs)}</TableCell><TableCell className="text-right tabular-nums">{number.format(item.fichesCompletes)}</TableCell><TableCell><div className="flex items-center gap-3"><Progress value={item.completude} className="w-20" /><span className="w-10 text-right text-sm tabular-nums">{item.completude}%</span></div></TableCell></TableRow>)}<TableRow className="border-t-2 bg-muted/30 font-semibold hover:bg-muted/30"><TableCell>Total</TableCell><TableCell className="text-right">{number.format(total.total)}</TableCell><TableCell className="text-right">{number.format(total.hommes)}</TableCell><TableCell className="text-right">{number.format(total.femmes)}</TableCell><TableCell className="text-right">{number.format(total.actifs)}</TableCell><TableCell className="text-right">{number.format(total.inactifs)}</TableCell><TableCell className="text-right">{number.format(total.fiches)}</TableCell><TableCell><div className="flex items-center gap-3"><Progress value={completeness} className="w-20" /><span className="w-10 text-right text-sm">{completeness}%</span></div></TableCell></TableRow></TableBody></Table></div><p className="text-xs text-muted-foreground">Complétude calculée sur le nom, le sexe, le rattachement, le téléphone, l’e-mail et le statut.</p></section>
}
