"use client"

import { apiFetch } from "@/lib/api/client"

import {useMemo,useState} from "react"
import {Plus,Search,Users} from "lucide-react"
import {toast} from "sonner"
import {ActorSearchSelect} from "@/components/dashboard/actor-search-select"
import {AthleteParticipations} from "@/components/dashboard/athlete-participations"
import {Avatar,AvatarFallback} from "@/components/ui/avatar"
import {Badge} from "@/components/ui/badge"
import {Button} from "@/components/ui/button"
import {Input} from "@/components/ui/input"
import {Label} from "@/components/ui/label"
import {Select,SelectContent,SelectItem,SelectTrigger,SelectValue} from "@/components/ui/select"
import {Sheet,SheetContent,SheetDescription,SheetHeader,SheetTitle} from "@/components/ui/sheet"
import {Textarea} from "@/components/ui/textarea"
import type {CampaignEngagement,CompetitionParticipant,CompetitionProgram,CompetitionReferences} from "@/lib/competitions/types"
import type {AthleteSelection} from "@/lib/equipes-nationales/types"

const ALL="TOUS", TYPES=["ATHLETE","COACH","OFFICIEL","ARBITRE","MEDECIN","AUTRE"] as const
const TYPE_LABELS:Record<string,string>={ATHLETE:"Athlètes",COACH:"Entraîneurs",OFFICIEL:"Officiels",ARBITRE:"Arbitres",MEDECIN:"Médecins",AUTRE:"Autres"}
const empty={id_engagement_campagne:"",id_type_acteur:"COACH",id_acteur_coc:"",id_role_staff:"",date_debut:"",date_fin:"",observation:""}

export function CompetitionParticipants({competitionId,initialRows,engagements,programs,references,participationReferences,federations,canEdit}:{competitionId:string;initialRows:CompetitionParticipant[];engagements:CampaignEngagement[];programs:CompetitionProgram[];references:CompetitionReferences;participationReferences:{statuses:{id:string;label:string}[];selections:AthleteSelection[]};federations:{id:string;label:string}[];canEdit:boolean}){
 const[rows,setRows]=useState(initialRows),[query,setQuery]=useState(""),[sport,setSport]=useState(ALL),[type,setType]=useState(ALL),[open,setOpen]=useState(false),[form,setForm]=useState(empty),[actors,setActors]=useState<{id:string;label:string}[]>([]),[roles,setRoles]=useState<{id:string;label:string}[]>([]),[saving,setSaving]=useState(false),[loadingActors,setLoadingActors]=useState(false)
 const sports=useMemo(()=>[...new Map(rows.map(row=>[row.sport_id,row.sport_label])).entries()].sort((a,b)=>a[1].localeCompare(b[1],"fr")),[rows])
 const filtered=useMemo(()=>rows.filter(row=>(sport===ALL||row.sport_id===sport)&&(type===ALL||row.id_type_acteur===type)&&(!query||`${row.actor_label} ${row.id_acteur_coc}`.toLocaleLowerCase("fr").includes(query.toLocaleLowerCase("fr")))),[rows,query,sport,type])
 const groups=useMemo(()=>sports.map(([sportId,sportLabel])=>({sportId,sportLabel,types:TYPES.map(actorType=>({actorType,label:TYPE_LABELS[actorType],rows:filtered.filter(row=>row.sport_id===sportId&&row.id_type_acteur===actorType)})).filter(group=>group.rows.length)})).filter(group=>group.types.length),[filtered,sports])
 async function loadActors(actorType:string){setLoadingActors(true);setActors([]);setRoles([]);setForm(current=>({...current,id_type_acteur:actorType,id_acteur_coc:"",id_role_staff:""}));try{const response=await apiFetch(`/api/competitions/${encodeURIComponent(competitionId)}/participants?actorType=${encodeURIComponent(actorType)}`,{cache:"no-store"}),result=await response.json();if(!response.ok)throw new Error(result.error);const existing=new Set(rows.filter(row=>row.id_type_acteur===actorType).map(row=>row.id_acteur_coc));setActors((result.actors||[]).filter((actor:{id:string})=>!existing.has(actor.id)));setRoles(result.roles||[])}catch(error){toast.error(error instanceof Error?error.message:String(error))}finally{setLoadingActors(false)}}
 function show(){setForm(empty);setActors([]);setRoles([]);setOpen(true);void loadActors("COACH")}
 async function save(){setSaving(true);try{const response=await apiFetch(`/api/competitions/${encodeURIComponent(competitionId)}/participants`,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({row:form})}),result=await response.json();if(!response.ok)throw new Error(result.error);setRows(current=>current.some(row=>row.id_participation_acteur===result.row.id_participation_acteur)?current:[...current,result.row]);setOpen(false);toast.success("Acteur COC ajouté à la compétition.")}catch(error){toast.error(error instanceof Error?error.message:String(error))}finally{setSaving(false)}}
 const engagement=engagements.find(row=>row.id_engagement_campagne===form.id_engagement_campagne),program=programs.find(row=>row.id_programme_competition===engagement?.id_programme_competition),event=references.events?.find(row=>row.id===program?.id_epreuve),selectedSport=references.sports?.find(row=>row.id===event?.sportId)?.label||event?.sportId
 return <div className="space-y-5">
  <div className="flex flex-wrap items-center justify-between gap-3"><div><h2 className="text-lg font-semibold">Participants <span className="text-muted-foreground">({rows.length})</span></h2><p className="text-sm text-muted-foreground">Regroupés par sport puis par type d’acteur.</p></div>{canEdit&&<Button onClick={show}><Plus className="mr-2 h-4 w-4"/>Ajouter un acteur COC</Button>}</div>
  <div className="grid gap-3 rounded-xl border bg-muted/20 p-3 md:grid-cols-[1fr_220px_220px]"><div className="relative"><Search className="absolute left-3 top-2.5 h-4 w-4 text-muted-foreground"/><Input className="pl-9" value={query} onChange={event=>setQuery(event.target.value)} placeholder="Rechercher par nom ou identifiant"/></div><Filter value={sport} onChange={setSport} placeholder="Tous les sports" options={sports.map(([id,label])=>({id,label}))}/><Filter value={type} onChange={setType} placeholder="Tous les types" options={TYPES.map(id=>({id,label:TYPE_LABELS[id]}))}/></div>
  {!groups.length?<div className="rounded-xl border border-dashed py-12 text-center text-sm text-muted-foreground"><Users className="mx-auto mb-3 h-8 w-8"/>Aucun participant ne correspond aux critères.</div>:groups.map(group=><section key={group.sportId} className="overflow-hidden rounded-xl border"><div className="flex items-center justify-between bg-muted/40 px-4 py-3"><h3 className="font-semibold">{group.sportLabel}</h3><Badge variant="secondary">{group.types.reduce((sum,item)=>sum+item.rows.length,0)}</Badge></div>{group.types.map(actorGroup=><div key={actorGroup.actorType} className="border-t"><div className="flex items-center gap-2 px-4 py-2 text-xs font-semibold uppercase tracking-wide text-muted-foreground"><span>{actorGroup.label}</span><span>{actorGroup.rows.length}</span></div>{actorGroup.rows.map(row=><div key={row.id_participation_acteur} className="grid min-h-14 items-center gap-3 border-t px-4 py-2 sm:grid-cols-[40px_1.4fr_1fr_1fr_auto]"><Avatar className="h-9 w-9"><AvatarFallback>{(row.actor_label||row.id_acteur_coc).split(/\s+/).slice(0,2).map(word=>word[0]).join("").toUpperCase()}</AvatarFallback></Avatar><div className="min-w-0"><p className="truncate font-medium">{row.actor_label||row.id_acteur_coc}</p><p className="truncate text-xs text-muted-foreground">{row.id_acteur_coc}</p></div><p className="truncate text-sm">{row.role_label||TYPE_LABELS[row.id_type_acteur]}</p><p className="truncate text-sm text-muted-foreground">{row.campaign_label}</p><Badge variant={row.id_statut_participation==="PARTICIPANT"?"default":"outline"}>{row.id_statut_participation}</Badge></div>)}</div>)}</section>)}
  <div className="border-t pt-5"><AthleteParticipations competitionId={competitionId} engagements={engagements} initialRows={rows.filter(row=>row.id_type_acteur==="ATHLETE")} references={participationReferences} federations={federations} canEdit={canEdit}/></div>
  <Sheet open={open} onOpenChange={setOpen}><SheetContent className="w-full overflow-y-auto sm:max-w-xl"><SheetHeader><SheetTitle>Ajouter un acteur COC</SheetTitle><SheetDescription>Les athlètes restent ajoutés via leurs sélections.</SheetDescription></SheetHeader><div className="space-y-4 px-4"><Field label="Engagement / campagne *"><Select value={form.id_engagement_campagne} onValueChange={value=>setForm({...form,id_engagement_campagne:value})}><SelectTrigger><SelectValue placeholder="Sélectionner"/></SelectTrigger><SelectContent>{engagements.map(row=><SelectItem key={row.id_engagement_campagne} value={row.id_engagement_campagne}>{row.nom_campagne||row.id_campagne}</SelectItem>)}</SelectContent></Select></Field>{engagement&&<div className="grid grid-cols-2 gap-3 rounded-lg bg-muted/40 p-3 text-sm"><span>Programme : {event?.label||program?.id_programme_competition}</span><span>Sport : {selectedSport||"—"}</span></div>}<Field label="Type d’acteur *"><Select value={form.id_type_acteur} onValueChange={loadActors}><SelectTrigger><SelectValue/></SelectTrigger><SelectContent>{TYPES.filter(value=>value!=="ATHLETE").map(value=><SelectItem key={value} value={value}>{TYPE_LABELS[value]}</SelectItem>)}</SelectContent></Select></Field><Field label="Acteur *"><ActorSearchSelect disabled={loadingActors} value={form.id_acteur_coc} onValueChange={value=>setForm({...form,id_acteur_coc:value})} options={actors} placeholder={loadingActors?"Chargement…":"Rechercher un acteur"}/></Field><Field label={form.id_type_acteur==="ARBITRE"?"Rôle (facultatif)":"Rôle *"}><Select value={form.id_role_staff||"AUCUN"} onValueChange={value=>setForm({...form,id_role_staff:value==="AUCUN"?"":value})}><SelectTrigger><SelectValue/></SelectTrigger><SelectContent><SelectItem value="AUCUN">Non renseigné</SelectItem>{roles.map(role=><SelectItem key={role.id} value={role.id}>{role.label}</SelectItem>)}</SelectContent></Select></Field><div className="grid grid-cols-2 gap-3"><Field label="Date de début *"><Input type="date" value={form.date_debut} onChange={event=>setForm({...form,date_debut:event.target.value})}/></Field><Field label="Date de fin"><Input type="date" value={form.date_fin} onChange={event=>setForm({...form,date_fin:event.target.value})}/></Field></div><Field label="Observation"><Textarea value={form.observation} onChange={event=>setForm({...form,observation:event.target.value})}/></Field><div className="flex justify-end gap-2"><Button variant="outline" onClick={()=>setOpen(false)}>Annuler</Button><Button disabled={saving} onClick={save}>{saving?"Enregistrement…":"Ajouter"}</Button></div></div></SheetContent></Sheet>
 </div>
}

function Filter({value,onChange,placeholder,options}:{value:string;onChange:(value:string)=>void;placeholder:string;options:{id:string;label:string}[]}){return <Select value={value} onValueChange={onChange}><SelectTrigger><SelectValue placeholder={placeholder}/></SelectTrigger><SelectContent><SelectItem value={ALL}>{placeholder}</SelectItem>{options.map(option=><SelectItem key={option.id} value={option.id}>{option.label}</SelectItem>)}</SelectContent></Select>}
function Field({label,children}:{label:string;children:React.ReactNode}){return <div className="space-y-2"><Label>{label}</Label>{children}</div>}
