"use client"

import { useEffect, useMemo, useState } from "react"
import { Medal, Pencil, Plus, Trash2 } from "lucide-react"
import { toast } from "sonner"
import { AlertDialog, AlertDialogAction, AlertDialogCancel, AlertDialogContent, AlertDialogDescription, AlertDialogFooter, AlertDialogHeader, AlertDialogTitle } from "@/components/ui/alert-dialog"
import { Badge } from "@/components/ui/badge"
import { Button } from "@/components/ui/button"
import { Input } from "@/components/ui/input"
import { Label } from "@/components/ui/label"
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select"
import { Sheet, SheetContent, SheetDescription, SheetHeader, SheetTitle } from "@/components/ui/sheet"
import { Table, TableBody, TableCell, TableHead, TableHeader, TableRow } from "@/components/ui/table"
import { Textarea } from "@/components/ui/textarea"
import { Tooltip, TooltipContent, TooltipProvider, TooltipTrigger } from "@/components/ui/tooltip"
import { loadCompetitionUnits } from "@/lib/competitions/client-units"
import { participatingUnitMedalLabel } from "@/lib/competitions/medals"
import type { CompetitionMedal, CompetitionProgram, CompetitionReferences, CompetitionResult, ParticipatingUnit } from "@/lib/competitions/types"

type Option={id:string;label:string}
const empty={id_resultat_logique:"",id_distinction:"",date_obtention:"",observation:""}

export function CompetitionMedals({competitionId,initialRows,results,programs,competitionReferences,distinctions,canEdit}:{competitionId:string;initialRows:CompetitionMedal[];results:CompetitionResult[];programs:CompetitionProgram[];competitionReferences:CompetitionReferences;distinctions:Option[];canEdit:boolean}){
 const[rows,setRows]=useState(initialRows),[units,setUnits]=useState<ParticipatingUnit[]>([]),[open,setOpen]=useState(false),[editing,setEditing]=useState(""),[form,setForm]=useState(empty),[saving,setSaving]=useState(false),[deleting,setDeleting]=useState<CompetitionMedal|null>(null)
 const currentResults=useMemo(()=>results.filter(row=>row.est_version_courante==="OUI"),[results])
 useEffect(()=>{let active=true;void loadCompetitionUnits(competitionId).then(value=>{if(active)setUnits(value)}).catch(()=>undefined);return()=>{active=false}},[competitionId])
 const unitLabel=(id:string)=>participatingUnitMedalLabel(units.find(item=>item.id_unite_participante===id),id)
 const eventLabel=(result:CompetitionResult)=>{const program=programs.find(item=>item.id_programme_competition===result.id_programme_competition);return competitionReferences.events?.find(item=>item.id===program?.id_epreuve)?.label||program?.id_epreuve||"Épreuve non renseignée"}
 const resultOptions=currentResults.map(result=>({id:result.id_resultat_logique,label:`${eventLabel(result)} · ${unitLabel(result.id_unite_participante)}`}))
 const medalLabel=(id:string)=>distinctions.find(item=>item.id===id)?.label||id
 function show(row?:CompetitionMedal){setEditing(row?.id_medaille||"");setForm(row?{id_resultat_logique:row.id_resultat_logique,id_distinction:row.id_distinction,date_obtention:row.date_obtention,observation:row.observation}:empty);setOpen(true)}
 async function save(){setSaving(true);try{const response=await fetch(`/api/competitions/${encodeURIComponent(competitionId)}/medailles`,{method:editing?"PUT":"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({id:editing,row:form})}),payload=await response.json();if(!response.ok)throw new Error(payload.error||"Enregistrement impossible.");const selected=currentResults.find(item=>item.id_resultat_logique===form.id_resultat_logique),row={...payload.row,id_unite_participante:selected?.id_unite_participante||"",unit_label:selected?unitLabel(selected.id_unite_participante):"",event_label:selected?eventLabel(selected):""};setRows(value=>editing?value.map(item=>item.id_medaille===editing?row:item):[row,...value]);setOpen(false);toast.success(editing?"Médaille modifiée.":"Médaille ajoutée.")}catch(error){toast.error(error instanceof Error?error.message:String(error))}finally{setSaving(false)}}
 async function remove(){if(!deleting)return;setSaving(true);try{const response=await fetch(`/api/competitions/${encodeURIComponent(competitionId)}/medailles`,{method:"DELETE",headers:{"Content-Type":"application/json"},body:JSON.stringify({id:deleting.id_medaille})}),payload=await response.json();if(!response.ok)throw new Error(payload.error||"Suppression impossible.");setRows(value=>value.filter(item=>item.id_medaille!==deleting.id_medaille));setDeleting(null);toast.success("Médaille supprimée.")}catch(error){toast.error(error instanceof Error?error.message:String(error))}finally{setSaving(false)}}
 return <section className="min-w-0 space-y-4" aria-labelledby="medals-title"><div className="flex flex-wrap items-center justify-between gap-3"><div><h3 id="medals-title" className="flex items-center gap-2 font-semibold"><Medal className="h-4 w-4"/>Médailles obtenues</h3><p className="text-sm text-muted-foreground">Récompenses rattachées au résultat logique et à son unité participante.</p></div>{canEdit&&<Button onClick={()=>show()} disabled={!resultOptions.length||!distinctions.length}><Plus className="mr-2 h-4 w-4"/>Ajouter une médaille</Button>}</div><div className="min-w-0 overflow-hidden rounded-lg border"><Table><TableHeader><TableRow><TableHead>Date</TableHead><TableHead>Unité</TableHead><TableHead>Médaille</TableHead>{canEdit&&<TableHead className="w-24 text-right">Actions</TableHead>}</TableRow></TableHeader><TableBody>{rows.map(row=><TableRow key={row.id_medaille}><TableCell className="whitespace-normal">{row.date_obtention||"—"}</TableCell><TableCell className="max-w-72 whitespace-normal"><p className="font-medium">{row.unit_label||"Unité non renseignée"}</p><p className="text-xs text-muted-foreground">{row.event_label||"Épreuve non renseignée"}</p></TableCell><TableCell><Badge variant="secondary">{medalLabel(row.id_distinction)}</Badge></TableCell>{canEdit&&<TableCell><div className="flex justify-end gap-1"><IconAction label="Modifier la médaille" onClick={()=>show(row)}><Pencil className="h-4 w-4"/></IconAction><IconAction label="Supprimer la médaille" onClick={()=>setDeleting(row)}><Trash2 className="h-4 w-4"/></IconAction></div></TableCell>}</TableRow>)}{!rows.length&&<TableRow><TableCell colSpan={canEdit?4:3} className="h-24 text-center text-muted-foreground">Aucune médaille enregistrée pour cette compétition</TableCell></TableRow>}</TableBody></Table></div>
 <Sheet open={open} onOpenChange={setOpen}><SheetContent className="w-full overflow-y-auto sm:max-w-xl"><SheetHeader><SheetTitle>{editing?"Modifier la médaille":"Ajouter une médaille"}</SheetTitle><SheetDescription>La récompense est liée au résultat logique, indépendamment de ses corrections.</SheetDescription></SheetHeader><div className="space-y-4 px-4"><Field label="Résultat concerné *"><Select value={form.id_resultat_logique} onValueChange={value=>setForm({...form,id_resultat_logique:value})}><SelectTrigger><SelectValue placeholder="Sélectionner une épreuve et une unité"/></SelectTrigger><SelectContent>{resultOptions.map(item=><SelectItem key={item.id} value={item.id}>{item.label}</SelectItem>)}</SelectContent></Select></Field><Field label="Médaille *"><Select value={form.id_distinction} onValueChange={value=>setForm({...form,id_distinction:value})}><SelectTrigger><SelectValue placeholder="Sélectionner"/></SelectTrigger><SelectContent>{distinctions.map(item=><SelectItem key={item.id} value={item.id}>{item.label}</SelectItem>)}</SelectContent></Select></Field><Field label="Date d’obtention *"><Input type="date" value={form.date_obtention} onChange={event=>setForm({...form,date_obtention:event.target.value})}/></Field><Field label="Observation"><Textarea value={form.observation} onChange={event=>setForm({...form,observation:event.target.value})}/></Field><div className="flex justify-end gap-2"><Button variant="outline" onClick={()=>setOpen(false)}>Annuler</Button><Button disabled={saving} onClick={save}>Enregistrer</Button></div></div></SheetContent></Sheet>
 <AlertDialog open={Boolean(deleting)} onOpenChange={value=>{if(!value)setDeleting(null)}}><AlertDialogContent><AlertDialogHeader><AlertDialogTitle>Supprimer cette médaille ?</AlertDialogTitle><AlertDialogDescription>Cette action supprimera définitivement la médaille de {deleting?.unit_label||"l’unité sélectionnée"}. Elle sera refusée si une dépendance métier est détectée.</AlertDialogDescription></AlertDialogHeader><AlertDialogFooter><AlertDialogCancel>Annuler</AlertDialogCancel><AlertDialogAction disabled={saving} onClick={remove}>Confirmer la suppression</AlertDialogAction></AlertDialogFooter></AlertDialogContent></AlertDialog></section>
}
function Field({label,children}:{label:string;children:React.ReactNode}){return <div className="space-y-2"><Label>{label}</Label>{children}</div>}
function IconAction({label,onClick,children}:{label:string;onClick:()=>void;children:React.ReactNode}){return <TooltipProvider><Tooltip><TooltipTrigger asChild><Button type="button" variant="ghost" size="icon" aria-label={label} onClick={onClick}>{children}</Button></TooltipTrigger><TooltipContent>{label}</TooltipContent></Tooltip></TooltipProvider>}
