"use client"

import { useEffect, useMemo, useState } from "react"
import { Pencil, Plus, UserX } from "lucide-react"
import { toast } from "sonner"
import { Badge } from "@/components/ui/badge"
import { Button } from "@/components/ui/button"
import { Checkbox } from "@/components/ui/checkbox"
import { Dialog, DialogContent, DialogDescription, DialogFooter, DialogHeader, DialogTitle } from "@/components/ui/dialog"
import { Input } from "@/components/ui/input"
import { Label } from "@/components/ui/label"
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select"
import type { EntityContact } from "@/lib/federations/entity-contacts-model"

type Data = { contacts: EntityContact[]; options: { id: string; typeId: string; nom: string }[]; types: { id: string; label: string }[] }
type Form = { id_type_acteur: string; id_acteur_coc: string; fonction_contact: string; est_contact_principal: boolean; statut: string; observation: string }
const empty: Form = { id_type_acteur: "", id_acteur_coc: "", fonction_contact: "", est_contact_principal: false, statut: "ACTIF", observation: "" }
const missing = "Non renseigné"

export function EntityContactsSection({ entityId, canWrite }: { entityId: string; canWrite: boolean }) {
  const [data, setData] = useState<Data>({ contacts: [], options: [], types: [] }), [loading, setLoading] = useState(true)
  const [open, setOpen] = useState(false), [saving, setSaving] = useState(false), [editing, setEditing] = useState<EntityContact | null>(null)
  const [form, setForm] = useState<Form>(empty)
  const actors = useMemo(() => data.options.filter((item) => item.typeId === form.id_type_acteur), [data.options, form.id_type_acteur])
  useEffect(() => { let active = true; void fetch(`/api/federations/contacts?entityId=${encodeURIComponent(entityId)}`).then(async (res) => { const body = await res.json(); if (!res.ok) throw new Error(body.error); if (active) setData(body) }).catch((e) => toast.error(e instanceof Error ? e.message : "Contacts indisponibles.")).finally(() => { if (active) setLoading(false) }); return () => { active = false } }, [entityId])
  const start = (contact?: EntityContact) => { setEditing(contact || null); setForm(contact ? { id_type_acteur: contact.id_type_acteur, id_acteur_coc: contact.id_acteur_coc, fonction_contact: contact.fonction_contact, est_contact_principal: contact.est_contact_principal, statut: contact.statut, observation: contact.observation } : empty); setOpen(true) }
  const save = async () => { setSaving(true); try { const res = await fetch("/api/federations/contacts", { method: editing ? "PUT" : "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ id: editing?.id_contact_entite, row: { ...form, id_entite: entityId } }) }); const body = await res.json(); if (!res.ok) throw new Error(body.error || "Enregistrement refusé."); setData(body); setOpen(false); toast.success(editing ? "Personne de contact modifiée." : "Personne de contact ajoutée.") } catch (e) { toast.error(e instanceof Error ? e.message : "Enregistrement refusé.") } finally { setSaving(false) } }
  const deactivate = async (contact: EntityContact) => { const res = await fetch("/api/federations/contacts", { method: "PUT", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ id: contact.id_contact_entite, row: { statut: "INACTIF", est_contact_principal: false } }) }); const body = await res.json(); if (!res.ok) return toast.error(body.error || "Désactivation refusée."); setData(body); toast.success("Relation de contact désactivée.") }
  return <section className="min-w-0 space-y-4" aria-labelledby={`contacts-${entityId}`}>
    <div className="flex flex-wrap items-center justify-between gap-3"><div><h3 id={`contacts-${entityId}`} className="text-lg font-semibold">Personnes de contact</h3><p className="text-sm text-muted-foreground">Désignations explicites auprès de l’entité.</p></div>{canWrite && <Button size="sm" variant="outline" onClick={() => start()}><Plus className="h-4 w-4" />Ajouter une personne de contact</Button>}</div>
    {loading ? <p className="text-sm text-muted-foreground">Chargement…</p> : !data.contacts.length ? <p className="rounded-lg border border-dashed p-4 text-sm text-muted-foreground">Aucune personne de contact désignée.</p> : <div className="grid gap-3 xl:grid-cols-2">{data.contacts.map((contact) => <article key={contact.id_contact_entite} className="min-w-0 rounded-lg border p-4"><div className="mb-3 flex items-start justify-between gap-3"><div className="min-w-0"><p className="break-words font-semibold">{contact.nom_complet || missing}</p><p className="text-sm text-muted-foreground">{contact.type_acteur}</p></div><div className="flex shrink-0 gap-1">{canWrite && <><Button size="icon" variant="ghost" aria-label="Modifier" onClick={() => start(contact)}><Pencil className="h-4 w-4" /></Button>{contact.statut === "ACTIF" && <Button size="icon" variant="ghost" aria-label="Désactiver" onClick={() => void deactivate(contact)}><UserX className="h-4 w-4" /></Button>}</>}</div></div><dl className="grid min-w-0 gap-3 text-sm sm:grid-cols-2"><div><dt className="text-muted-foreground">Fonction</dt><dd className="break-words font-medium">{contact.fonction_contact || missing}</dd></div><div><dt className="text-muted-foreground">Téléphone</dt><dd className="break-all">{contact.telephone || missing}</dd></div><div><dt className="text-muted-foreground">E-mail</dt><dd className="break-all">{contact.email || missing}</dd></div><div className="flex flex-wrap gap-2"><Badge variant={contact.est_contact_principal ? "default" : "outline"}>{contact.est_contact_principal ? "Principal" : "Secondaire"}</Badge><Badge variant="outline">{contact.statut}</Badge></div></dl></article>)}</div>}
    <Dialog open={open} onOpenChange={setOpen}><DialogContent className="max-h-[90vh] overflow-y-auto sm:max-w-xl"><DialogHeader><DialogTitle>{editing ? "Modifier la personne de contact" : "Ajouter une personne de contact"}</DialogTitle><DialogDescription>L’acteur reste géré dans sa fiche d’origine.</DialogDescription></DialogHeader><div className="grid gap-4 sm:grid-cols-2"><div className="space-y-2"><Label>Type d’acteur *</Label><Select value={form.id_type_acteur} onValueChange={(value) => setForm((old) => ({ ...old, id_type_acteur: value, id_acteur_coc: "" }))}><SelectTrigger><SelectValue placeholder="Sélectionner" /></SelectTrigger><SelectContent>{data.types.map((type) => <SelectItem key={type.id} value={type.id}>{type.label}</SelectItem>)}</SelectContent></Select></div><div className="space-y-2"><Label>Acteur existant *</Label><Select value={form.id_acteur_coc} onValueChange={(value) => setForm((old) => ({ ...old, id_acteur_coc: value }))}><SelectTrigger><SelectValue placeholder="Sélectionner" /></SelectTrigger><SelectContent>{actors.map((actor) => <SelectItem key={actor.id} value={actor.id}>{actor.nom}</SelectItem>)}</SelectContent></Select></div><div className="space-y-2 sm:col-span-2"><Label>Fonction auprès de l’entité *</Label><Input value={form.fonction_contact} onChange={(e) => setForm((old) => ({ ...old, fonction_contact: e.target.value }))} /></div><div className="space-y-2"><Label>Statut *</Label><Select value={form.statut} onValueChange={(value) => setForm((old) => ({ ...old, statut: value }))}><SelectTrigger><SelectValue /></SelectTrigger><SelectContent><SelectItem value="ACTIF">Actif</SelectItem><SelectItem value="INACTIF">Inactif</SelectItem></SelectContent></Select></div><div className="flex items-center gap-2 pt-7"><Checkbox id="principal" checked={form.est_contact_principal} onCheckedChange={(value) => setForm((old) => ({ ...old, est_contact_principal: value === true }))} /><Label htmlFor="principal">Contact principal</Label></div><div className="space-y-2 sm:col-span-2"><Label>Observation</Label><Input value={form.observation} onChange={(e) => setForm((old) => ({ ...old, observation: e.target.value }))} /></div></div><DialogFooter><Button variant="outline" onClick={() => setOpen(false)}>Annuler</Button><Button disabled={saving} onClick={() => void save()}>{saving ? "Enregistrement…" : "Enregistrer"}</Button></DialogFooter></DialogContent></Dialog>
  </section>
}
