import { Table, TableBody, TableCell, TableHead, TableHeader, TableRow } from "@/components/ui/table"
import type { NationalTeamsDashboardStats } from "@/lib/equipes-nationales/dashboard"

const number = new Intl.NumberFormat("fr-FR")
export function NationalTeamsSummarySection({ stats }: { stats: NationalTeamsDashboardStats }) {
  const total = { total: stats.totalTeams, active: stats.activeTeams, inactive: stats.inactiveTeams, members: stats.totalMembers }
  const cells = (item: typeof total) => <><TableCell className="text-right tabular-nums">{number.format(item.total)}</TableCell><TableCell className="text-right tabular-nums">{number.format(item.active)}</TableCell><TableCell className="text-right tabular-nums">{number.format(item.inactive)}</TableCell><TableCell className="text-right tabular-nums">{number.format(item.members)}</TableCell></>
  return <section className="space-y-4"><div><h2 className="text-lg font-semibold">Équipes nationales</h2><p className="text-sm text-muted-foreground">Répartition des équipes et membres actifs distincts par sport</p></div><div className="overflow-x-auto rounded-lg border"><Table><TableHeader><TableRow><TableHead>Sport</TableHead><TableHead className="text-right">Équipes</TableHead><TableHead className="text-right">Actives</TableHead><TableHead className="text-right">Inactives</TableHead><TableHead className="text-right">Membres actifs</TableHead></TableRow></TableHeader><TableBody>{stats.sports.map((item) => <TableRow key={item.key}><TableCell>{item.label}</TableCell>{cells(item)}</TableRow>)}{!stats.sports.length && <TableRow><TableCell colSpan={5} className="h-24 text-center text-muted-foreground">Aucune équipe nationale enregistrée.</TableCell></TableRow>}<TableRow className="border-t-2 bg-muted/30 font-semibold"><TableCell>Total</TableCell>{cells(total)}</TableRow></TableBody></Table></div></section>
}
