"use client"
import { useMemo, useState } from "react"
import { useRouter } from "next/navigation"
import { Pencil, Plus } from "lucide-react"
import { toast } from "sonner"
import { Badge } from "@/components/ui/badge"
import { Button } from "@/components/ui/button"
import { Card, CardContent } from "@/components/ui/card"
import { Input } from "@/components/ui/input"
import { Label } from "@/components/ui/label"
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select"
import { Sheet, SheetContent, SheetDescription, SheetHeader, SheetTitle } from "@/components/ui/sheet"
import { Textarea } from "@/components/ui/textarea"
import type { NationalTeamCampaign } from "@/lib/equipes-nationales/types"

const empty = { nom_campagne: "", date_debut: "", date_fin: "", objectif: "", statut: "PLANIFIEE", observation: "" }
const statuses = [["PLANIFIEE", "Planifiée"], ["ACTIF", "Active"], ["CLOTUREE", "Clôturée"], ["ANNULEE", "Annulée"]]
export function NationalTeamCampaigns({ teamId, initialRows, canEdit }: { teamId: string; initialRows: NationalTeamCampaign[]; canEdit: boolean }) {
  const router = useRouter()
  const [rows, setRows] = useState(initialRows), [open, setOpen] = useState(false), [editing, setEditing] = useState(""), [form, setForm] = useState(empty), [saving, setSaving] = useState(false)
  const chronologicalRows = useMemo(() => [...rows].sort((a, b) => (a.date_debut || "9999-12-31").localeCompare(b.date_debut || "9999-12-31") || a.nom_campagne.localeCompare(b.nom_campagne, "fr", { sensitivity: "base" })), [rows])
  function show(row?: NationalTeamCampaign) { setEditing(row?.id_campagne || ""); setForm(row ? { nom_campagne: row.nom_campagne, date_debut: row.date_debut, date_fin: row.date_fin, objectif: row.objectif, statut: row.statut, observation: row.observation } : empty); setOpen(true) }
  async function save() { setSaving(true); try { const response = await fetch(`/api/equipes-nationales/${encodeURIComponent(teamId)}/campagnes`, { method: editing ? "PUT" : "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ id: editing, row: form }) }), result = await response.json(); if (!response.ok) throw new Error(result.error); setRows((current) => editing ? current.map((row) => row.id_campagne === editing ? result.row : row) : [...current, result.row]); setOpen(false); toast.success(editing ? "Campagne modifiée." : "Campagne créée."); router.refresh() } catch (error) { toast.error(error instanceof Error ? error.message : String(error)) } finally { setSaving(false) } }
  return <><div className="space-y-4"><div className="flex items-center justify-between gap-3"><div><h3 className="font-semibold">Campagnes</h3><p className="text-sm text-muted-foreground">Contextes temporels de mobilisation de l’équipe nationale.</p></div>{canEdit && <Button onClick={() => show()}><Plus className="mr-2 h-4 w-4" />Ajouter</Button>}</div><div className="grid gap-3 md:grid-cols-2 xl:grid-cols-3">{chronologicalRows.map((row) => <Card key={row.id_campagne}><CardContent className="space-y-3 p-4"><div className="flex justify-between gap-2"><div><p className="font-medium">{row.nom_campagne}</p><p className="text-xs text-muted-foreground">{row.id_campagne}</p></div>{canEdit && <Button size="icon" variant="ghost" onClick={() => show(row)} aria-label="Modifier"><Pencil className="h-4 w-4" /></Button>}</div><Badge variant="outline">{row.statut}</Badge><p className="text-sm">{row.date_debut}{row.date_fin ? ` — ${row.date_fin}` : " — en cours"}</p><p className="text-sm text-muted-foreground">{row.objectif || "Objectif non renseigné"}</p></CardContent></Card>)}</div>{!rows.length && <p className="rounded-lg border p-6 text-center text-muted-foreground">Aucune campagne enregistrée.</p>}</div><Sheet open={open} onOpenChange={setOpen}><SheetContent className="w-full overflow-y-auto sm:max-w-lg"><SheetHeader><SheetTitle>{editing ? "Modifier la campagne" : "Ajouter une campagne"}</SheetTitle><SheetDescription>L’équipe permanente reste inchangée.</SheetDescription></SheetHeader><div className="space-y-4 px-4"><Field label="Nom *"><Input value={form.nom_campagne} onChange={(e)=>setForm({...form,nom_campagne:e.target.value})}/></Field><Field label="Début *"><Input type="date" value={form.date_debut} onChange={(e)=>setForm({...form,date_debut:e.target.value})}/></Field><Field label="Fin"><Input type="date" value={form.date_fin} onChange={(e)=>setForm({...form,date_fin:e.target.value})}/></Field><Field label="Statut *"><Select value={form.statut} onValueChange={(v)=>setForm({...form,statut:v})}><SelectTrigger><SelectValue/></SelectTrigger><SelectContent>{statuses.map(([id,label])=><SelectItem key={id} value={id}>{label}</SelectItem>)}</SelectContent></Select></Field><Field label="Objectif"><Textarea value={form.objectif} onChange={(e)=>setForm({...form,objectif:e.target.value})}/></Field><Field label="Observation"><Textarea value={form.observation} onChange={(e)=>setForm({...form,observation:e.target.value})}/></Field><div className="flex justify-end gap-2"><Button variant="outline" onClick={()=>setOpen(false)}>Annuler</Button><Button disabled={saving} onClick={save}>Enregistrer</Button></div></div></SheetContent></Sheet></>
}
function Field({label,children}:{label:string;children:React.ReactNode}) { return <div className="space-y-2"><Label>{label}</Label>{children}</div> }
