import "server-only"
import { appendSheetRow, getSheetHeaders, getSheetRows, getSheetsRows, updateSheetCells } from "@/lib/google/sheets"
import { getReferentialSpreadsheetId } from "@/lib/federations/config"
import { getFederationOptions } from "@/lib/federations/options"
import { getActors } from "@/lib/activites/data"
import { getNationalTeamsSpreadsheetId } from "./config"
import { NATIONAL_TEAM_HEADERS, NATIONAL_TEAM_MEMBER_HEADERS, NATIONAL_TEAM_ROLES, type ActorType, type NationalTeam, type NationalTeamMember, type NationalTeamReferences } from "./types"
import { validateMemberInput, validateTeamInput } from "./validation"
const clean=(value:unknown)=>String(value??"").trim(), TEAM_SHEET="EQUIPES_NATIONALES", MEMBER_SHEET="EQUIPES_NATIONALES_MEMBRES"
async function assertHeaders(sheetName:string, expected:readonly string[]){const headers=await getSheetHeaders({sheetName,spreadsheetId:getNationalTeamsSpreadsheetId()});const missing=expected.filter(x=>!headers.includes(x));if(missing.length)throw new Error(`Mapping ${sheetName} incomplet : ${missing.join(", ")}`)}
const mapTeam=(row:Record<string,string>)=>Object.fromEntries(NATIONAL_TEAM_HEADERS.map(key=>[key,clean(row[key])])) as NationalTeam
const mapMember=(row:Record<string,string>)=>Object.fromEntries(NATIONAL_TEAM_MEMBER_HEADERS.map(key=>[key,clean(row[key])])) as NationalTeamMember
const nextId=(values:string[],prefix:string,padding=3)=>`${prefix}${String(values.reduce((max,value)=>{const match=value.match(new RegExp(`^${prefix}(\\d+)$`,"i"));return match?Math.max(max,Number(match[1])):max},0)+1).padStart(padding,"0")}`
export async function getNationalTeams(){await assertHeaders(TEAM_SHEET,NATIONAL_TEAM_HEADERS);return(await getSheetRows({sheetName:TEAM_SHEET,spreadsheetId:getNationalTeamsSpreadsheetId()})).map(mapTeam).filter(x=>x.id_equipe_nationale)}
export async function getNationalTeam(id:string){return(await getNationalTeams()).find(x=>x.id_equipe_nationale===clean(id))}
export async function getNationalTeamMembers(teamId?:string,actorId?:string){await assertHeaders(MEMBER_SHEET,NATIONAL_TEAM_MEMBER_HEADERS);return(await getSheetRows({sheetName:MEMBER_SHEET,spreadsheetId:getNationalTeamsSpreadsheetId()})).map(mapMember).filter(x=>x.id_membre_equipe_nationale&&(!teamId||x.id_equipe_nationale===teamId)&&(!actorId||x.id_acteur_coc===actorId))}
export async function getNationalTeamReferences():Promise<NationalTeamReferences>{const id=getReferentialSpreadsheetId();const[federations,refs]=await Promise.all([getFederationOptions(),getSheetsRows({sheetNames:["SPORTS","DISCIPLINES","CATEGORIES_AGE","SEXES"],spreadsheetId:id})]);let roles:{id:string;label:string}[]=NATIONAL_TEAM_ROLES.map(value=>({id:value,label:({ATHLETE:"Athlète",COACH_PRINCIPAL:"Coach principal",ASSISTANT_COACH:"Assistant coach",MEDECIN:"Médecin",PREPARATEUR:"Préparateur",SPARRING_PARTNER:"Sparring-partner",OFFICIEL:"Officiel",AUTRE:"Autre"}as Record<string,string>)[value]}));let rolesReferentialAvailable=false;try{const rows=await getSheetRows({sheetName:"ROLES_EQUIPE_NATIONALE",spreadsheetId:id});const found=rows.filter(x=>x.id_role_equipe_nationale).map(x=>({id:x.id_role_equipe_nationale,label:x.nom_role_equipe_nationale||x.id_role_equipe_nationale}));if(found.length){roles=found;rolesReferentialAvailable=true}}catch{}const ageCategories=refs.CATEGORIES_AGE.filter(x=>x.id_categorie_age).map(x=>({id:x.id_categorie_age,label:x.nom_categorie_age||x.id_categorie_age,parentId:x.id_discipline||x.id_sport}));return{federations:federations.map(x=>({id:x.id,label:x.sigle||x.nom,secondary:x.nom,parentId:x.idSport})),sports:refs.SPORTS.filter(x=>x.id_sport).map(x=>({id:x.id_sport,label:x.nom_sport})),disciplines:refs.DISCIPLINES.filter(x=>x.id_discipline).map(x=>({id:x.id_discipline,label:x.nom_discipline,parentId:x.id_sport})),ageCategories,sexes:refs.SEXES.filter(x=>x.id_sexe&&!/mixte/i.test(x.nom_sexe||"")).map(x=>({id:x.id_sexe,label:x.nom_sexe||x.id_sexe})),roles,ageCategoriesAvailable:ageCategories.length>0,rolesReferentialAvailable}}
export async function createNationalTeam(input:Record<string,unknown>){const row=validateTeamInput(input),refs=await getNationalTeamReferences();const federation=refs.federations.find(x=>x.id===row.id_federation);if(!federation)throw new Error("Fédération inconnue.");if(federation.parentId&&federation.parentId!==row.id_sport)throw new Error("Le sport ne correspond pas à la fédération.");if(row.id_discipline&&!refs.disciplines.some(x=>x.id===row.id_discipline&&x.parentId===row.id_sport))throw new Error("Discipline incohérente avec le sport.");const existing=await getNationalTeams(),created={id_equipe_nationale:nextId(existing.map(x=>x.id_equipe_nationale),"EQN"),...row};await appendSheetRow({sheetName:TEAM_SHEET,spreadsheetId:getNationalTeamsSpreadsheetId(),row:created});return created as NationalTeam}
export async function updateNationalTeam(id:string,input:Record<string,unknown>){const current=await getNationalTeam(id);if(!current)throw new Error("Équipe nationale introuvable.");const row=validateTeamInput({...input,id_federation:current.id_federation,id_sport:current.id_sport});await updateSheetCells({sheetName:TEAM_SHEET,spreadsheetId:getNationalTeamsSpreadsheetId(),idColumn:"id_equipe_nationale",idValue:id,updates:Object.entries(row).map(([column,value])=>({column,value}))});return{...current,...row}}
export async function getActorOptions(type:ActorType){return getActors(type)}
export async function createNationalTeamMember(teamId:string,input:Record<string,unknown>){if(!(await getNationalTeam(teamId)))throw new Error("Équipe nationale introuvable.");const row=validateMemberInput(input);if(!(await getActorOptions(row.id_type_acteur as ActorType)).some(x=>x.id===row.id_acteur_coc))throw new Error("Acteur introuvable ou type incohérent.");const existing=await getNationalTeamMembers();if(existing.some(x=>x.id_equipe_nationale===teamId&&x.id_acteur_coc===row.id_acteur_coc&&x.role_selection===row.role_selection&&x.date_debut===row.date_debut))throw new Error("Cette appartenance existe déjà pour la même période.");const created={id_membre_equipe_nationale:nextId(existing.map(x=>x.id_membre_equipe_nationale),"MEN"),id_equipe_nationale:teamId,...row};await appendSheetRow({sheetName:MEMBER_SHEET,spreadsheetId:getNationalTeamsSpreadsheetId(),row:created});return created as NationalTeamMember}
export async function updateNationalTeamMember(teamId:string,id:string,input:Record<string,unknown>){const current=(await getNationalTeamMembers(teamId)).find(x=>x.id_membre_equipe_nationale===id);if(!current)throw new Error("Membre introuvable.");const row=validateMemberInput({...input,id_acteur_coc:current.id_acteur_coc,id_type_acteur:current.id_type_acteur});await updateSheetCells({sheetName:MEMBER_SHEET,spreadsheetId:getNationalTeamsSpreadsheetId(),idColumn:"id_membre_equipe_nationale",idValue:id,updates:["role_selection","date_debut","date_fin","statut","observations"].map(column=>({column,value:row[column as keyof typeof row]}))});return{...current,...row,id_acteur_coc:current.id_acteur_coc,id_type_acteur:current.id_type_acteur}}
