import assert from "node:assert/strict"
import test from "node:test"
import { AuthorizationCommands } from "../../lib/users/authorization-commands.ts"
import { createManagedUser, updateManagedUser } from "../../lib/users/administration-workflows.ts"
import { AUDIT_LOG_HEADERS, AUDIT_LOG_SHEET, AUTH_ATTEMPT_HEADERS, AUTH_ATTEMPTS_SHEET, USER_AUTHORIZATION_HEADERS, USER_AUTHORIZATIONS_SHEET, USER_HEADERS, USERS_SHEET, type SheetRow, type UsersSheetsAdapter } from "../../lib/users/types.ts"
import { UsersRepository } from "../../lib/users/repository.ts"
class Memory implements UsersSheetsAdapter { rows: Record<string, SheetRow[]> = { [USERS_SHEET]: [], [USER_AUTHORIZATIONS_SHEET]: [], [AUTH_ATTEMPTS_SHEET]: [], [AUDIT_LOG_SHEET]: [] }; headers: Record<string, string[]> = { [USERS_SHEET]: [...USER_HEADERS], [USER_AUTHORIZATIONS_SHEET]: [...USER_AUTHORIZATION_HEADERS], [AUTH_ATTEMPTS_SHEET]: [...AUTH_ATTEMPT_HEADERS], [AUDIT_LOG_SHEET]: [...AUDIT_LOG_HEADERS] }; authorizationWrites = 0; failSecondAuthorization = false; async readHeaders(s: string) { return this.headers[s] } async readRows(s: string) { return this.rows[s].map((r) => ({ ...r })) } async appendRow(s: string, r: SheetRow) { if (s === USER_AUTHORIZATIONS_SHEET && this.failSecondAuthorization && ++this.authorizationWrites === 2) throw new Error("partial"); this.rows[s].push({ ...r }) } async updateRow(s: string, c: string, id: string, r: SheetRow) { const i = this.rows[s].findIndex((x) => x[c] === id); if (i < 0) throw new Error("missing"); this.rows[s][i] = { ...r } } }
test("crée un compte, audite et remet le secret une seule fois", async () => { const adapter = new Memory(), input = { adapter, actorId: "ADMIN-1", requestId: "REQ-1", nomComplet: "Nouvel utilisateur", email: "new@example.org", typeUser: "ADMIN" as const, estSuperAdmin: false, authorizations: [{ block: "AUT-SPT" as const, dateDebut: "2026-09-01" }], generateAccess: () => "Acces-Temporaire-2026" }; const first = await createManagedUser(input); assert.equal(first.status, "CREATED"); assert.equal(first.temporaryAccess, "Acces-Temporaire-2026"); assert.equal(adapter.rows[AUDIT_LOG_SHEET].length, 1); assert.ok(!JSON.stringify(adapter.rows).includes(first.temporaryAccess)); const second = await createManagedUser(input); assert.equal(second.status, "EXISTING"); assert.equal(second.temporaryAccess, null); assert.equal(adapter.rows[AUDIT_LOG_SHEET].length, 1) })
test("compense une création multi-feuilles partielle", async () => { const adapter = new Memory(); adapter.failSecondAuthorization = true; await assert.rejects(() => createManagedUser({ adapter, actorId: "ADMIN-1", requestId: "REQ-2", nomComplet: "Partiel", email: "partial@example.org", typeUser: "ADMIN", estSuperAdmin: false, authorizations: [{ block: "AUT-SPT", dateDebut: "2026-09-01" }, { block: "AUT-ADM", dateDebut: "2026-09-01" }], generateAccess: () => "Acces-Temporaire-2026" }), /compensée/); assert.equal((await new UsersRepository(adapter).getUsers())[0].statut, "INACTIF") })
test("refuse les périodes superposées et protège le dernier super-administrateur", async () => { const adapter = new Memory(); const created = await createManagedUser({ adapter, actorId: "ROOT", requestId: "REQ-3", nomComplet: "Root", email: "root@example.org", typeUser: "ADMIN", estSuperAdmin: true, authorizations: [], generateAccess: () => "Acces-Temporaire-2026" }); await new AuthorizationCommands(adapter).create({ idUser: created.user.idUser, idBlocAutorisation: "AUT-SPT", statut: "ACTIF", dateDebut: "2026-09-01", dateFin: "2026-09-30" }); await assert.rejects(() => new AuthorizationCommands(adapter).create({ idUser: created.user.idUser, idBlocAutorisation: "AUT-SPT", statut: "ACTIF", dateDebut: "2026-09-30", dateFin: null }), /chevauchantes/); await assert.rejects(() => updateManagedUser({ adapter, actorId: "ROOT", requestId: "REQ-4", target: created.user, patch: { statut: "INACTIF" } }), /dernier super-administrateur/) })
