"use client"

import Link from "next/link"
import { useState } from "react"
import { useRouter } from "next/navigation"
import { ArrowLeft, Pencil, Plus } from "lucide-react"
import { toast } from "sonner"
import { CompetitionForm, competitionToForm } from "@/components/dashboard/competition-form"
import { Header } from "@/components/dashboard/header"
import { Badge } from "@/components/ui/badge"
import { Button } from "@/components/ui/button"
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card"
import { Input } from "@/components/ui/input"
import { Label } from "@/components/ui/label"
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select"
import { Sheet, SheetContent, SheetDescription, SheetHeader, SheetTitle } from "@/components/ui/sheet"
import { Table, TableBody, TableCell, TableHead, TableHeader, TableRow } from "@/components/ui/table"
import { Tabs, TabsContent, TabsList, TabsTrigger } from "@/components/ui/tabs"
import { Textarea } from "@/components/ui/textarea"
import { competitionStatusLabels, formatCompetitionPeriod, formatDateFr } from "@/lib/competitions/format"
import type { Competition, CompetitionReferences, TeamParticipation } from "@/lib/competitions/types"
import type { DocumentRecord } from "@/lib/documents/types"

const emptyTeam = { id_equipe_nationale: "", statut_participation: "PREVUE", date_engagement: "", observations: "" }
const formatSize = (value: string) => Number(value) > 0 ? `${Math.ceil(Number(value) / 1024)} Ko` : "—"

export default function CompetitionDetailClient({ competition: initial, references, participations: initialParticipations, teamsError, documents, documentsError, canEdit }: { competition: Competition; references: CompetitionReferences; participations: TeamParticipation[]; teamsError?: string; documents?: DocumentRecord[]; documentsError?: string; canEdit: boolean }) {
  const router = useRouter(); const [competition, setCompetition] = useState(initial); const [participations, setParticipations] = useState(initialParticipations); const [editOpen, setEditOpen] = useState(false); const [teamOpen, setTeamOpen] = useState(false); const [editTeamId, setEditTeamId] = useState(""); const [form, setForm] = useState(competitionToForm(initial)); const [teamForm, setTeamForm] = useState(emptyTeam); const [saving, setSaving] = useState(false)
  const typeLabel = references.types.find((item) => item.id === competition.id_type_competition)?.label || competition.id_type_competition || "—"
  const teamMap = new Map(references.teams.map((team) => [team.id, team]))
  async function saveCompetition() { setSaving(true); try { const response = await fetch("/api/competitions", { method: "PUT", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ id: competition.id_competition, row: form }) }); const result = await response.json(); if (!response.ok) throw new Error(result.error); setCompetition(result.row); setEditOpen(false); toast.success("Compétition modifiée."); router.refresh() } catch (error) { toast.error(error instanceof Error ? error.message : String(error)) } finally { setSaving(false) } }
  function addTeam() { setEditTeamId(""); setTeamForm(emptyTeam); setTeamOpen(true) }
  function editTeam(item: TeamParticipation) { setEditTeamId(item.id_participation_equipe); setTeamForm({ id_equipe_nationale: item.id_equipe_nationale, statut_participation: item.statut_participation || "PREVUE", date_engagement: item.date_engagement, observations: item.observations }); setTeamOpen(true) }
  async function saveTeam() { setSaving(true); try { const response = await fetch(`/api/competitions/${encodeURIComponent(competition.id_competition)}/equipes-nationales`, { method: editTeamId ? "PUT" : "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ id: editTeamId, row: teamForm }) }); const result = await response.json(); if (!response.ok) throw new Error(result.error); setParticipations((current) => editTeamId ? current.map((item) => item.id_participation_equipe === editTeamId ? result.row : item) : [...current, result.row]); setTeamOpen(false); toast.success(editTeamId ? "Participation modifiée." : "Équipe nationale ajoutée."); router.refresh() } catch (error) { toast.error(error instanceof Error ? error.message : String(error)) } finally { setSaving(false) } }
  const fields = [["ID", competition.id_competition], ["Nom", competition.nom_competition], ["Type", typeLabel], ["Édition", competition.edition], ["Niveau", competition.niveau_competition], ["Période", formatCompetitionPeriod(competition.date_debut, competition.date_fin)], ["Pays", competition.pays], ["Ville", competition.ville], ["Lieu", competition.lieu], ["Statut", competitionStatusLabels[competition.statut_normalise]], ["Observations", competition.observations]]
  return <div className="min-h-screen"><Header title={competition.nom_competition} subtitle="Fiche compétition" /><main className="space-y-5 p-4 md:p-6"><Button asChild variant="ghost"><Link href="/dashboard/competitions"><ArrowLeft className="mr-2 h-4 w-4" />Retour à la liste</Link></Button>
    <Tabs defaultValue="general" className="space-y-4"><TabsList className="grid w-full max-w-xl grid-cols-3"><TabsTrigger value="general">Général</TabsTrigger><TabsTrigger value="teams">Équipes nationales</TabsTrigger><TabsTrigger value="documents">Documents</TabsTrigger></TabsList>
      <TabsContent value="general"><Card><CardHeader className="flex flex-row items-center justify-between"><CardTitle>Informations générales</CardTitle>{canEdit && <Button variant="outline" onClick={() => { setForm(competitionToForm(competition)); setEditOpen(true) }}><Pencil className="mr-2 h-4 w-4" />Modifier</Button>}</CardHeader><CardContent className="grid gap-5 sm:grid-cols-2 lg:grid-cols-3">{fields.map(([label, value]) => <div key={label}><p className="text-sm text-muted-foreground">{label}</p><p className="font-medium whitespace-pre-wrap">{value || "—"}</p></div>)}</CardContent></Card></TabsContent>
      <TabsContent value="teams"><Card><CardHeader className="flex flex-row items-center justify-between"><div><CardTitle>Équipes nationales</CardTitle>{!references.teamsAvailable && <p className="mt-1 text-sm text-amber-700">Le catalogue des équipes nationales doit être configuré.</p>}</div>{canEdit && <Button disabled={!references.teamsAvailable} onClick={addTeam}><Plus className="mr-2 h-4 w-4" />Ajouter une équipe nationale</Button>}</CardHeader><CardContent className="overflow-x-auto p-0">{teamsError ? <p className="p-6 text-destructive">{teamsError}</p> : <Table><TableHeader><TableRow><TableHead>Équipe nationale</TableHead><TableHead>Fédération</TableHead><TableHead>Sport</TableHead><TableHead>Discipline</TableHead><TableHead>Statut participation</TableHead><TableHead>Date engagement</TableHead><TableHead /></TableRow></TableHeader><TableBody>{participations.map((item) => { const team = teamMap.get(item.id_equipe_nationale); return <TableRow key={item.id_participation_equipe}><TableCell className="font-medium">{team?.label || item.id_equipe_nationale}</TableCell><TableCell>{team?.federation || "—"}</TableCell><TableCell>{team?.sport || "—"}</TableCell><TableCell>{team?.discipline || "—"}</TableCell><TableCell><Badge variant="outline">{item.statut_participation || "NON RENSEIGNÉ"}</Badge></TableCell><TableCell>{formatDateFr(item.date_engagement)}</TableCell><TableCell>{canEdit && <Button variant="ghost" size="sm" onClick={() => editTeam(item)}>Modifier</Button>}</TableCell></TableRow>})}{!participations.length && <TableRow><TableCell colSpan={7} className="h-24 text-center text-muted-foreground">Aucune équipe nationale rattachée.</TableCell></TableRow>}</TableBody></Table>}</CardContent></Card></TabsContent>
      <TabsContent value="documents"><Card><CardHeader><CardTitle>Documents</CardTitle></CardHeader><CardContent className="overflow-x-auto p-0">{documentsError ? <p className="p-6 text-destructive">{documentsError}</p> : documents === undefined ? <p className="p-6 text-muted-foreground">Documents accessibles au rôle COC.</p> : <Table><TableHeader><TableRow><TableHead>Document</TableHead><TableHead>Type</TableHead><TableHead>Taille</TableHead><TableHead /></TableRow></TableHeader><TableBody>{documents.map((document) => <TableRow key={document.id_document}><TableCell className="font-medium">{document.nom_document}</TableCell><TableCell>{document.id_type_document || "—"}</TableCell><TableCell>{formatSize(document.taille)}</TableCell><TableCell><Button asChild variant="ghost" size="sm"><Link href={`/dashboard/documents/${document.id_document}`}>Voir</Link></Button></TableCell></TableRow>)}{!documents.length && <TableRow><TableCell colSpan={4} className="h-24 text-center text-muted-foreground">Aucun document lié.</TableCell></TableRow>}</TableBody></Table>}</CardContent></Card></TabsContent>
    </Tabs>
    <Sheet open={editOpen} onOpenChange={setEditOpen}><SheetContent className="w-full overflow-y-auto sm:max-w-2xl"><SheetHeader><SheetTitle>Modifier la compétition</SheetTitle><SheetDescription>L’identifiant {competition.id_competition} reste immuable.</SheetDescription></SheetHeader><div className="px-4"><CompetitionForm value={form} onChange={setForm} types={references.types} saving={saving} submitLabel="Enregistrer les modifications" onSubmit={saveCompetition} onCancel={() => setEditOpen(false)} /></div></SheetContent></Sheet>
    <Sheet open={teamOpen} onOpenChange={setTeamOpen}><SheetContent className="w-full overflow-y-auto sm:max-w-lg"><SheetHeader><SheetTitle>{editTeamId ? "Modifier la participation" : "Ajouter une équipe nationale"}</SheetTitle><SheetDescription>{editTeamId ? "L’équipe nationale reste immuable." : "Sélectionnez une équipe existante."}</SheetDescription></SheetHeader><div className="space-y-5 px-4"><div className="space-y-2"><Label>Équipe nationale *</Label><Select disabled={Boolean(editTeamId)} value={teamForm.id_equipe_nationale} onValueChange={(value) => setTeamForm({ ...teamForm, id_equipe_nationale: value })}><SelectTrigger><SelectValue placeholder="Sélectionner" /></SelectTrigger><SelectContent>{references.teams.filter((team) => editTeamId || !participations.some((item) => item.id_equipe_nationale === team.id)).map((team) => <SelectItem key={team.id} value={team.id}>{team.label}{team.federation ? ` · ${team.federation}` : ""}</SelectItem>)}</SelectContent></Select></div><div className="space-y-2"><Label>Statut participation *</Label><Select value={teamForm.statut_participation} onValueChange={(value) => setTeamForm({ ...teamForm, statut_participation: value })}><SelectTrigger><SelectValue /></SelectTrigger><SelectContent><SelectItem value="PREVUE">Prévue</SelectItem><SelectItem value="CONFIRMEE">Confirmée</SelectItem><SelectItem value="ENGAGEE">Engagée</SelectItem><SelectItem value="ANNULEE">Annulée</SelectItem></SelectContent></Select></div><div className="space-y-2"><Label>Date d’engagement</Label><Input type="date" value={teamForm.date_engagement} onChange={(event) => setTeamForm({ ...teamForm, date_engagement: event.target.value })} /></div><div className="space-y-2"><Label>Observations</Label><Textarea value={teamForm.observations} onChange={(event) => setTeamForm({ ...teamForm, observations: event.target.value })} /></div><div className="flex justify-end gap-2"><Button variant="outline" onClick={() => setTeamOpen(false)}>Annuler</Button><Button disabled={saving} onClick={saveTeam}>{saving ? "Enregistrement…" : "Enregistrer"}</Button></div></div></SheetContent></Sheet>
  </main></div>
}
