"use client"
import Link from "next/link"
import {useMemo,useState} from "react"
import {useRouter} from "next/navigation"
import {ArrowLeft,Eye,Pencil} from "lucide-react"
import {toast} from "sonner"
import {CompetitionForm,competitionToForm} from "@/components/dashboard/competition-form"
import {CompetitionPrograms} from "./competition-programs"
import {CampaignEngagements} from "@/components/dashboard/campaign-engagements"
import {AthleteParticipations} from "@/components/dashboard/athlete-participations"
import {CompetitionResults} from "@/components/dashboard/competition-results"
import {CompetitionMedals} from "@/components/dashboard/competition-medals"
import {ParticipatingUnits} from "@/components/dashboard/participating-units"
import {Header} from "@/components/dashboard/header"
import {DataQualitySummary} from "@/components/dashboard/data-quality-summary"
import {Badge} from "@/components/ui/badge"
import {Button} from "@/components/ui/button"
import {Card,CardContent,CardHeader,CardTitle} from "@/components/ui/card"
import {Sheet,SheetContent,SheetDescription,SheetHeader,SheetTitle} from "@/components/ui/sheet"
import {Tabs,TabsContent,TabsList,TabsTrigger} from "@/components/ui/tabs"
import {Tooltip,TooltipContent,TooltipProvider,TooltipTrigger} from "@/components/ui/tooltip"
import {competitionStatusLabels,formatCompetitionPeriod} from "@/lib/competitions/format"
import type {AthleteParticipation,CampaignEngagement,Competition,CompetitionMedal,CompetitionProgram,CompetitionReferences,CompetitionResult} from "@/lib/competitions/types"
import type {AthleteSelection} from "@/lib/equipes-nationales/types"
import type {DocumentRecord} from "@/lib/documents/types"
import type {DataQualityReport} from "@/lib/competitions/quality"

type EngagementRefs={campaigns:{id:string;label:string;teamId:string;teamName:string;federationId:string;dateStart:string;dateEnd:string;status:string}[];statuses:{id:string;label:string}[];federations:{id:string;label:string}[]}
type ResultRefs={synthetics:{id:string;label:string}[];units:{id:string;label:string;type?:string}[];decisions:{id:string;label:string;federationId?:string;sportId?:string;disciplineId?:string}[];statuses:{id:string;label:string}[];federations:{id:string;label:string}[]}
const shown=(value?:string)=>value||"Non renseigné"
const label=(rows:{id:string;label:string}[],id?:string)=>rows.find((row)=>row.id===id)?.label||shown(id)

export default function CompetitionDetailClient({competition:initial,qualityReport,references,programs,programsError,engagements,engagementReferences,engagementsError,athleteParticipations,participationReferences,participationsError,results,resultReferences,resultsError,medals,medalReferences,medalsError,canEdit}:{competition:Competition;qualityReport:DataQualityReport;references:CompetitionReferences;programs:CompetitionProgram[];programsError?:string;engagements:CampaignEngagement[];engagementReferences:EngagementRefs;engagementsError?:string;athleteParticipations:AthleteParticipation[];participationReferences:{statuses:{id:string;label:string}[];selections:AthleteSelection[]};participationsError?:string;results:CompetitionResult[];resultReferences:ResultRefs;resultsError?:string;medals:CompetitionMedal[];medalReferences:{id:string;label:string}[];medalsError?:string;documents?:DocumentRecord[];documentsError?:string;canEdit:boolean}){
 const[competition,setCompetition]=useState(initial),[editOpen,setEditOpen]=useState(false),[form,setForm]=useState(competitionToForm(initial)),[saving,setSaving]=useState(false)
 const campaignMap=useMemo(()=>new Map(engagementReferences.campaigns.map((item)=>[item.id,item])),[engagementReferences.campaigns])
 const athleteRows=useMemo(()=>engagements.flatMap((engagement)=>participationReferences.selections.filter((selection)=>selection.id_campagne===engagement.id_campagne).map((selection)=>({selection,engagement,participation:athleteParticipations.find((item)=>item.id_engagement_campagne===engagement.id_engagement_campagne&&item.id_selection===selection.id_selection)}))),[athleteParticipations,engagements,participationReferences.selections])
 async function saveCompetition(){setSaving(true);try{const response=await fetch("/api/competitions",{method:"PUT",headers:{"Content-Type":"application/json"},body:JSON.stringify({id:competition.id_competition,row:form})}),result=await response.json();if(!response.ok)throw new Error(result.message||result.error);setCompetition(result.row);setEditOpen(false);toast.success("Compétition modifiée.")}catch(error){toast.error(error instanceof Error?error.message:String(error))}finally{setSaving(false)}}
 const openEdit=()=>{setForm(competitionToForm(competition));setEditOpen(true)}
 const contextFields=[["Type de compétition",label(references.types,competition.id_type_competition)],["Niveau",label(references.levels||[],competition.niveau_competition)],["Caractère",competition.est_multisport==="OUI"?"Multisport":"Monosport"]]
 const scheduleFields=[["Date de début",competition.date_debut],["Date de fin",competition.date_fin],["Pays",competition.pays],["Ville",competition.ville],["Lieu",competition.lieu]]
 return <div className="min-h-screen min-w-0 overflow-x-hidden"><Header title={competition.nom_competition} subtitle={[competition.edition,formatCompetitionPeriod(competition.date_debut,competition.date_fin)].filter(Boolean).join(" · ")} actions={canEdit&&<Button onClick={openEdit} size="sm" variant="outline"><Pencil className="h-4 w-4"/>Modifier</Button>}/><main className="min-w-0 space-y-6 p-4 md:p-6">
  <Button asChild variant="ghost" size="sm" className="gap-2"><Link href="/dashboard/competitions"><ArrowLeft className="h-4 w-4"/>Retour aux compétitions</Link></Button>
  <Card className="min-w-0 border-border/50"><Tabs defaultValue="general" className="w-full"><CardHeader className="pb-0"><TabsList className="grid h-auto w-full grid-cols-2 lg:grid-cols-5"><TabsTrigger value="general">Général</TabsTrigger><TabsTrigger value="programs">Programmes</TabsTrigger><TabsTrigger value="participants">Participants</TabsTrigger><TabsTrigger value="teams">Équipes / unités</TabsTrigger><TabsTrigger value="results">Résultats</TabsTrigger></TabsList></CardHeader><CardContent className="pt-6">
   <TabsContent value="general" className="mt-0 min-w-0 space-y-6"><div className="grid min-w-0 grid-cols-1 items-start gap-6 lg:grid-cols-3">
    <section className="min-w-0 self-start rounded-xl border border-border/60 bg-muted/10 p-5 lg:col-span-1" aria-labelledby="competition-identity-title"><div className="flex flex-col items-center text-center"><div className="mb-4 flex h-16 w-16 items-center justify-center rounded-2xl bg-primary/10 text-xl font-semibold text-primary">{competition.nom_competition.split(/\s+/).filter(Boolean).slice(0,2).map((word)=>word[0]).join("").toUpperCase()||"CO"}</div><h2 id="competition-identity-title" className="break-words text-xl font-semibold">{shown(competition.nom_competition)}</h2><p className="mt-1 text-sm text-muted-foreground">{shown(competition.edition)}</p><Badge variant="outline" className="mt-3">{shown(competitionStatusLabels[competition.statut_normalise])}</Badge><dl className="mt-5 w-full space-y-3 border-t border-border/60 pt-4 text-sm"><div className="flex min-w-0 justify-between gap-3"><dt className="text-muted-foreground">Identifiant</dt><dd className="break-all text-right font-mono text-xs font-medium">{shown(competition.id_competition)}</dd></div><div className="flex justify-between gap-3"><dt className="text-muted-foreground">Programmes</dt><dd className="font-medium tabular-nums">{programs.length}</dd></div><div className="flex justify-between gap-3"><dt className="text-muted-foreground">Engagements</dt><dd className="font-medium tabular-nums">{engagements.length}</dd></div><div className="flex justify-between gap-3"><dt className="text-muted-foreground">Participants</dt><dd className="font-medium tabular-nums">{athleteParticipations.filter((item)=>item.id_statut_participation==="PARTICIPANT").length}</dd></div></dl></div></section>
    <div className="min-w-0 space-y-7 lg:col-span-2"><InfoSection title="Cadre sportif" fields={contextFields}/><InfoSection title="Calendrier et localisation" fields={scheduleFields}/>{competition.observations&&<InfoSection title="Observation" fields={[["Note",competition.observations]]}/>}</div>
   </div><div className="border-t border-border pt-6"><DataQualitySummary report={qualityReport}/></div></TabsContent>
   <TabsContent value="programs" className="mt-0 space-y-4">{programsError?<SectionError message={programsError}/>:<CompetitionPrograms competitionId={competition.id_competition} initialRows={programs} references={references} canEdit={canEdit}/>}</TabsContent>
   <TabsContent value="participants" className="mt-0 space-y-4"><SectionTitle title="Participants" action={canEdit?"Gérer les participants":undefined}/>{participationsError?<SectionError message={participationsError}/>:<><ParticipantSection title="Athlètes" empty="Aucun athlète enregistré pour cette compétition.">{athleteRows.map(({selection,engagement,participation})=>{const campaign=campaignMap.get(engagement.id_campagne);return <article key={`${engagement.id_engagement_campagne}-${selection.id_selection}`} className="grid min-w-0 items-center gap-2 rounded-lg border p-4 sm:grid-cols-2 xl:grid-cols-[1.4fr_1fr_1fr_1fr_1fr_auto]"><p className="break-words font-medium">{shown(selection.athlete_label||selection.id_athlete)}</p><p>{label(engagementReferences.federations,campaign?.federationId)}</p><p>{shown(selection.id_poste||"Athlète")}</p><Badge variant="secondary">{shown(selection.id_statut_selection)}</Badge><Badge variant="outline">{shown(participation?.id_statut_participation)}</Badge><TooltipProvider><Tooltip><TooltipTrigger asChild><Button asChild variant="ghost" size="icon"><Link href={`/dashboard/acteurs/athletes/${encodeURIComponent(selection.id_athlete)}`} aria-label={`Consulter ${selection.athlete_label||selection.id_athlete}`}><Eye className="h-4 w-4"/></Link></Button></TooltipTrigger><TooltipContent>Consulter l’athlète</TooltipContent></Tooltip></TooltipProvider></article>})}</ParticipantSection>{["Entraîneurs","Médecins","Arbitres","Officiels","Autres"].map((title)=><ParticipantSection key={title} title={title} empty={`Aucun ${title.toLocaleLowerCase("fr").replace(/s$/,"")} enregistré pour cette compétition.`}/>)}</>}
    {!participationsError&&<Card><CardContent className="p-4"><AthleteParticipations competitionId={competition.id_competition} engagements={engagements} initialRows={athleteParticipations} references={participationReferences} federations={engagementReferences.federations} canEdit={canEdit}/></CardContent></Card>}</TabsContent>
   <TabsContent value="teams" className="mt-0 space-y-4">{engagementsError?<SectionError message={engagementsError}/>:<CampaignEngagements competitionId={competition.id_competition} programs={programs} initialRows={engagements} references={engagementReferences} competitionReferences={references} canEdit={canEdit}/>} {!engagementsError&&!participationsError&&<ParticipatingUnits competitionId={competition.id_competition} engagements={engagements} participants={athleteParticipations} programs={programs} references={references} canEdit={canEdit}/>}</TabsContent>
   <TabsContent value="results" className="mt-0 space-y-8"><SectionTitle title="Résultats" action={canEdit?"Ajouter ou modifier un résultat":undefined}/>{resultsError?<SectionError message={resultsError}/>:<CompetitionResults competitionId={competition.id_competition} engagements={engagements} programs={programs} competitionReferences={references} initialRows={results} references={resultReferences} canEdit={canEdit}/>}<div className="border-t pt-6">{medalsError?<SectionError message={medalsError}/>:<CompetitionMedals competitionId={competition.id_competition} initialRows={medals} results={results} programs={programs} competitionReferences={references} distinctions={medalReferences} canEdit={canEdit}/>}</div></TabsContent>
   </CardContent></Tabs></Card>
  <Sheet open={editOpen} onOpenChange={setEditOpen}><SheetContent className="w-full overflow-y-auto sm:max-w-2xl"><SheetHeader><SheetTitle>Modifier la compétition</SheetTitle><SheetDescription>L’identifiant {competition.id_competition} reste immuable.</SheetDescription></SheetHeader><div className="px-4"><CompetitionForm value={form} onChange={setForm} types={references.types} levels={references.levels} statuses={references.statuses} saving={saving} submitLabel="Enregistrer les modifications" onSubmit={saveCompetition} onCancel={()=>setEditOpen(false)}/></div></SheetContent></Sheet>
 </main></div>
}
function SectionTitle({title,action}:{title:string;action?:string}){return <div className="flex flex-col gap-2 sm:flex-row sm:items-center sm:justify-between"><h2 className="text-lg font-semibold">{title}</h2>{action&&<p className="text-sm text-muted-foreground">{action}</p>}</div>}
function InfoSection({title,fields}:{title:string;fields:string[][]}){return <section className="min-w-0 space-y-4"><h3 className="text-sm font-semibold uppercase tracking-wide text-muted-foreground">{title}</h3><dl className="grid min-w-0 gap-x-6 gap-y-5 sm:grid-cols-2">{fields.map(([name,value])=><div key={name} className="min-w-0"><dt className="text-sm text-muted-foreground">{name}</dt><dd className="break-words font-medium whitespace-pre-wrap">{shown(value)}</dd></div>)}</dl></section>}
function ParticipantSection({title,empty,children}:{title:string;empty:string;children?:React.ReactNode}){return <Card className="min-w-0"><CardHeader><CardTitle className="text-base">{title}</CardTitle></CardHeader><CardContent className="space-y-3">{children||<p className="py-4 text-sm text-muted-foreground">{empty}</p>}</CardContent></Card>}
function SectionError({message}:{message:string}){const router=useRouter();return <Card><CardContent role="alert" className="flex flex-wrap items-center justify-between gap-3 p-6 text-destructive"><span>{message} Les autres sections restent disponibles.</span><Button type="button" variant="outline" size="sm" onClick={()=>router.refresh()}>Réessayer</Button></CardContent></Card>}
