"use client"

import Link from "next/link"
import { useRouter } from "next/navigation"
import { ChevronLeft, ChevronRight, Eye, Plus, Search } from "lucide-react"
import { useMemo, useState } from "react"
import { toast } from "sonner"
import { Header } from "@/components/dashboard/header"
import { NationalTeamForm, emptyNationalTeamForm } from "@/components/dashboard/national-team-form"
import { Badge } from "@/components/ui/badge"
import { Button } from "@/components/ui/button"
import { Card, CardContent } from "@/components/ui/card"
import { Input } from "@/components/ui/input"
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select"
import { Sheet, SheetContent, SheetDescription, SheetHeader, SheetTitle } from "@/components/ui/sheet"
import { Table, TableBody, TableCell, TableHead, TableHeader, TableRow } from "@/components/ui/table"
import { isActiveNationalTeamMember, type NationalTeam, type NationalTeamMember, type NationalTeamReferences } from "@/lib/equipes-nationales/types"

const neutral = (value?: string) => value || "Non renseigné"

export default function Client({ teams, members, references, canEdit, initialCreate = false, loadError }: { teams: NationalTeam[]; members: NationalTeamMember[]; references: NationalTeamReferences; canEdit: boolean; initialCreate?: boolean; loadError?: string }) {
  const router = useRouter()
  const [query, setQuery] = useState(""), [federation, setFederation] = useState("tous"), [status, setStatus] = useState("tous"), [page, setPage] = useState(1), [pageSize, setPageSize] = useState(10)
  const [createOpen, setCreateOpen] = useState(initialCreate), [form, setForm] = useState(emptyNationalTeamForm), [saving, setSaving] = useState(false)
  const label = (items: NationalTeamReferences["sports"], id: string) => items.find((item) => item.id === id)?.label || id || "Non renseigné"
  const activeMembers = members.filter((member) => isActiveNationalTeamMember(member)); const distinctActiveMembers = new Set(activeMembers.map((member) => member.id_acteur_coc)).size
  const rows = useMemo(() => teams.filter((team) => { const text = [team.id_equipe_nationale, team.nom_equipe_nationale, label(references.federations, team.id_federation), label(references.sports, team.id_sport), label(references.disciplines, team.id_discipline), label(references.ageCategories, team.id_categorie_age), label(references.sexes, team.id_sexe), team.statut].join(" ").toLocaleLowerCase("fr"); return (!query || text.includes(query.toLocaleLowerCase("fr"))) && (federation === "tous" || team.id_federation === federation) && (status === "tous" || team.statut === status) }).sort((a, b) => a.nom_equipe_nationale.localeCompare(b.nom_equipe_nationale, "fr", { sensitivity: "base" })), [teams, query, federation, status, references])
  const pageCount = Math.max(1, Math.ceil(rows.length / pageSize)), currentPage = Math.min(page, pageCount), visible = rows.slice((currentPage - 1) * pageSize, currentPage * pageSize)
  const changeFilter = (action: () => void) => { action(); setPage(1) }
  const count = (id: string) => new Set(activeMembers.filter((member) => member.id_equipe_nationale === id).map((member) => member.id_acteur_coc)).size
  const detail = (team: NationalTeam) => <Button asChild variant="ghost" size="icon"><Link href={`/dashboard/equipes-nationales/${encodeURIComponent(team.id_equipe_nationale)}`} aria-label={`Voir ${team.nom_equipe_nationale}`} title="Ouvrir la fiche"><Eye className="h-4 w-4" /></Link></Button>
  async function createTeam() { setSaving(true); try { const response = await fetch("/api/equipes-nationales", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ row: form }) }); const result = await response.json(); if (!response.ok) throw new Error(result.error || "Création impossible."); toast.success("Équipe nationale créée."); setCreateOpen(false); router.push(`/dashboard/equipes-nationales/${result.row.id_equipe_nationale}`); router.refresh() } catch (error) { toast.error(error instanceof Error ? error.message : String(error)) } finally { setSaving(false) } }
  return <div className="min-w-0"><Header title="Équipes nationales" subtitle="Unités permanentes, campagnes et engagements" /><main className="min-w-0 space-y-6 p-4 md:p-6">{loadError ? <p role="alert" className="rounded-lg border border-destructive/30 p-4 text-destructive">{loadError}</p> : <><div className="flex justify-end">{canEdit && <Button onClick={() => { setForm(emptyNationalTeamForm); setCreateOpen(true) }}><Plus className="mr-2 h-4 w-4" />Nouvelle équipe nationale</Button>}</div><div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-4">{[["Total équipes nationales", teams.length], ["Actives", teams.filter((team) => team.statut === "ACTIF").length], ["Inactives", teams.filter((team) => team.statut !== "ACTIF").length], ["Membres actifs", distinctActiveMembers]].map(([title, value]) => <Card key={title}><CardContent className="p-4"><p className="text-2xl font-semibold tabular-nums">{value}</p><p className="text-sm text-muted-foreground">{title}</p></CardContent></Card>)}</div>
    <div className="grid gap-3 md:grid-cols-[minmax(16rem,1fr)_minmax(13rem,18rem)_minmax(11rem,14rem)]"><div className="relative"><Search className="absolute left-3 top-3 h-4 w-4 text-muted-foreground" /><Input className="pl-9" aria-label="Rechercher une équipe nationale" placeholder="Nom, identifiant, fédération ou sport…" value={query} onChange={(event) => changeFilter(() => setQuery(event.target.value))} /></div><Filter label="Fédération" value={federation} set={(value) => changeFilter(() => setFederation(value))} all="tous" options={references.federations} /><Select value={status} onValueChange={(value) => changeFilter(() => setStatus(value))}><SelectTrigger aria-label="Filtrer par statut"><SelectValue /></SelectTrigger><SelectContent><SelectItem value="tous">Tous les statuts</SelectItem><SelectItem value="ACTIF">Actif</SelectItem><SelectItem value="INACTIF">Inactif</SelectItem></SelectContent></Select></div>
    <Card className="min-w-0 overflow-hidden"><CardContent className="p-0"><div className="hidden lg:block"><Table><TableHeader><TableRow><TableHead>Équipe nationale</TableHead><TableHead>Fédération</TableHead><TableHead>Sport / discipline</TableHead><TableHead>Catégorie / sexe</TableHead><TableHead className="text-right">Membres actifs</TableHead><TableHead>Statut</TableHead><TableHead className="w-14" /></TableRow></TableHeader><TableBody>{visible.map((team) => <TableRow key={team.id_equipe_nationale}><TableCell className="max-w-64 whitespace-normal"><p className="break-words font-medium">{neutral(team.nom_equipe_nationale)}</p><p className="font-mono text-xs text-muted-foreground">{neutral(team.id_equipe_nationale)}</p></TableCell><TableCell className="max-w-52 whitespace-normal">{label(references.federations, team.id_federation)}</TableCell><TableCell className="max-w-52 whitespace-normal"><p>{label(references.sports, team.id_sport)}</p><p className="text-xs text-muted-foreground">{label(references.disciplines, team.id_discipline)}</p></TableCell><TableCell className="max-w-44 whitespace-normal"><p>{label(references.ageCategories, team.id_categorie_age)}</p><p className="text-xs text-muted-foreground">{label(references.sexes, team.id_sexe)}</p></TableCell><TableCell className="text-right tabular-nums">{count(team.id_equipe_nationale)}</TableCell><TableCell><Badge variant="outline">{neutral(team.statut)}</Badge></TableCell><TableCell>{detail(team)}</TableCell></TableRow>)}{!visible.length && <TableRow><TableCell colSpan={7} className="h-24 text-center text-muted-foreground">{teams.length ? "Aucune équipe nationale ne correspond aux filtres." : "Aucune équipe nationale enregistrée."}</TableCell></TableRow>}</TableBody></Table></div>
      <div className="grid min-w-0 gap-3 p-3 sm:grid-cols-2 lg:hidden">{visible.map((team) => <article key={team.id_equipe_nationale} className="min-w-0 rounded-lg border p-4"><div className="flex items-start justify-between gap-3"><div className="min-w-0"><h2 className="break-words font-semibold">{neutral(team.nom_equipe_nationale)}</h2><p className="font-mono text-xs text-muted-foreground">{neutral(team.id_equipe_nationale)}</p></div>{detail(team)}</div><div className="mt-3 space-y-1 text-sm"><p className="break-words">{label(references.federations, team.id_federation)}</p><p className="break-words">{label(references.sports, team.id_sport)} · {label(references.disciplines, team.id_discipline)}</p><p className="break-words text-muted-foreground">{label(references.ageCategories, team.id_categorie_age)} · {label(references.sexes, team.id_sexe)}</p><div className="flex items-center justify-between gap-2 pt-2"><Badge variant="outline">{neutral(team.statut)}</Badge><span className="text-xs text-muted-foreground">{count(team.id_equipe_nationale)} membre(s)</span></div></div></article>)}{!visible.length && <p className="py-10 text-center text-sm text-muted-foreground sm:col-span-2">{teams.length ? "Aucune équipe nationale ne correspond aux filtres." : "Aucune équipe nationale enregistrée."}</p>}</div>
    </CardContent></Card><div className="flex flex-col gap-3 sm:flex-row sm:items-center sm:justify-between"><p className="text-sm text-muted-foreground">{rows.length} résultat(s) · page {currentPage} sur {pageCount}</p><div className="flex items-center gap-2"><Select value={String(pageSize)} onValueChange={(value) => changeFilter(() => setPageSize(Number(value)))}><SelectTrigger className="w-24" aria-label="Résultats par page"><SelectValue /></SelectTrigger><SelectContent>{[10, 20, 50].map((size) => <SelectItem key={size} value={String(size)}>{size}</SelectItem>)}</SelectContent></Select><Button variant="outline" size="icon" disabled={currentPage <= 1} onClick={() => setPage(currentPage - 1)} aria-label="Page précédente"><ChevronLeft className="h-4 w-4" /></Button><Button variant="outline" size="icon" disabled={currentPage >= pageCount} onClick={() => setPage(currentPage + 1)} aria-label="Page suivante"><ChevronRight className="h-4 w-4" /></Button></div></div></>}<Sheet open={createOpen} onOpenChange={setCreateOpen}><SheetContent className="w-full overflow-y-auto sm:max-w-2xl"><SheetHeader><SheetTitle>Nouvelle équipe nationale</SheetTitle><SheetDescription>Créer une unité nationale permanente. Les campagnes seront ajoutées depuis sa fiche.</SheetDescription></SheetHeader><div className="px-4"><NationalTeamForm value={form} onChange={setForm} references={references} saving={saving} onSubmit={createTeam} onCancel={() => setCreateOpen(false)} /></div></SheetContent></Sheet></main></div>
}

function Filter({ label, value, set, all, options }: { label: string; value: string; set: (value: string) => void; all: string; options: NationalTeamReferences["sports"] }) { return <Select value={value} onValueChange={set}><SelectTrigger aria-label={`Filtrer par ${label.toLocaleLowerCase("fr")}`}><SelectValue placeholder={label} /></SelectTrigger><SelectContent><SelectItem value={all}>Toutes / tous</SelectItem>{options.map((item) => <SelectItem key={item.id} value={item.id}>{item.label}</SelectItem>)}</SelectContent></Select> }
