"use client"
import Link from "next/link"
import { Eye, Plus, Search } from "lucide-react"
import { useMemo, useState } from "react"
import { Header } from "@/components/dashboard/header"
import { Badge } from "@/components/ui/badge"
import { Button } from "@/components/ui/button"
import { Card, CardContent } from "@/components/ui/card"
import { Input } from "@/components/ui/input"
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select"
import { Table, TableBody, TableCell, TableHead, TableHeader, TableRow } from "@/components/ui/table"
import { isActiveNationalTeamMember, type NationalTeam, type NationalTeamMember, type NationalTeamReferences } from "@/lib/equipes-nationales/types"

export default function Client({ teams, members, references, canEdit, loadError }: { teams: NationalTeam[]; members: NationalTeamMember[]; references: NationalTeamReferences; canEdit: boolean; loadError?: string }) {
  const [query, setQuery] = useState(""), [federation, setFederation] = useState("tous"), [sport, setSport] = useState("tous"), [discipline, setDiscipline] = useState("toutes"), [sex, setSex] = useState("tous"), [age, setAge] = useState("toutes"), [status, setStatus] = useState("tous")
  const label = (items: NationalTeamReferences["sports"], id: string) => items.find((item) => item.id === id)?.label || id || "—"
  const disciplineOptions = references.disciplines.filter((item) => sport === "tous" || item.parentId === sport)
  const categoryOptions = references.ageCategories.filter((item) => discipline !== "toutes" ? item.parentId === discipline : sport === "tous" || item.parentId === sport)
  const activeMembers = members.filter((member) => isActiveNationalTeamMember(member))
  const distinctActiveMembers = new Set(activeMembers.map((member) => member.id_acteur_coc)).size
  const rows = useMemo(() => teams.filter((team) => { const text = [team.id_equipe_nationale, team.nom_equipe_nationale, label(references.federations, team.id_federation), label(references.sports, team.id_sport), label(references.disciplines, team.id_discipline), label(references.ageCategories, team.id_categorie_age), label(references.sexes, team.id_sexe), team.statut].join(" ").toLocaleLowerCase("fr"); return (!query || text.includes(query.toLocaleLowerCase("fr"))) && (federation === "tous" || team.id_federation === federation) && (sport === "tous" || team.id_sport === sport) && (discipline === "toutes" || team.id_discipline === discipline) && (sex === "tous" || team.id_sexe === sex) && (age === "toutes" || team.id_categorie_age === age) && (status === "tous" || team.statut === status) }).sort((a, b) => a.nom_equipe_nationale.localeCompare(b.nom_equipe_nationale, "fr", { sensitivity: "base" })), [teams, query, federation, sport, discipline, sex, age, status, references])
  const changeSport = (value: string) => { setSport(value); setDiscipline("toutes"); setAge("toutes") }
  const changeDiscipline = (value: string) => { setDiscipline(value); setAge("toutes") }
  return <div><Header title="Équipes nationales" subtitle="Unités nationales et appartenance des acteurs" /><main className="space-y-6 p-4 md:p-6">{loadError ? <p className="rounded-lg border border-destructive/30 p-4 text-destructive">{loadError}</p> : <><div className="flex justify-end">{canEdit && <Button asChild><Link href="/dashboard/equipes-nationales/nouveau"><Plus className="mr-2 h-4 w-4" />Nouvelle équipe nationale</Link></Button>}</div><div className="grid gap-3 sm:grid-cols-4">{[["Total équipes nationales", teams.length], ["Actives", teams.filter((team) => team.statut === "ACTIF").length], ["Inactives", teams.filter((team) => team.statut !== "ACTIF").length], ["Membres actifs", distinctActiveMembers]].map(([title, value]) => <Card key={title}><CardContent className="p-4"><p className="text-2xl font-semibold">{value}</p><p className="text-sm text-muted-foreground">{title}</p></CardContent></Card>)}</div>
    <div className="flex flex-wrap gap-2"><div className="relative min-w-64 flex-1"><Search className="absolute left-3 top-3 h-4 w-4" /><Input className="pl-9" placeholder="Rechercher une équipe…" value={query} onChange={(event) => setQuery(event.target.value)} /></div><Filter value={federation} set={setFederation} all="tous" options={references.federations} /><Filter value={sport} set={changeSport} all="tous" options={references.sports} /><Filter value={discipline} set={changeDiscipline} all="toutes" options={disciplineOptions} /><Filter value={age} set={setAge} all="toutes" options={categoryOptions} /><Filter value={sex} set={setSex} all="tous" options={references.sexes} /><Select value={status} onValueChange={setStatus}><SelectTrigger className="w-36"><SelectValue /></SelectTrigger><SelectContent><SelectItem value="tous">Tous statuts</SelectItem><SelectItem value="ACTIF">Actif</SelectItem><SelectItem value="INACTIF">Inactif</SelectItem></SelectContent></Select></div>
    <Card><CardContent className="overflow-x-auto p-0"><Table><TableHeader><TableRow><TableHead>ID</TableHead><TableHead>Équipe nationale</TableHead><TableHead>Fédération</TableHead><TableHead>Sport</TableHead><TableHead>Discipline</TableHead><TableHead>Catégorie</TableHead><TableHead>Sexe</TableHead><TableHead className="text-right">Membres actifs</TableHead><TableHead>Statut</TableHead><TableHead /></TableRow></TableHeader><TableBody>{rows.map((team) => <TableRow key={team.id_equipe_nationale}><TableCell className="font-mono text-xs">{team.id_equipe_nationale}</TableCell><TableCell className="font-medium">{team.nom_equipe_nationale}</TableCell><TableCell>{label(references.federations, team.id_federation)}</TableCell><TableCell>{label(references.sports, team.id_sport)}</TableCell><TableCell>{label(references.disciplines, team.id_discipline)}</TableCell><TableCell>{label(references.ageCategories, team.id_categorie_age)}</TableCell><TableCell>{label(references.sexes, team.id_sexe)}</TableCell><TableCell className="text-right">{new Set(activeMembers.filter((member) => member.id_equipe_nationale === team.id_equipe_nationale).map((member) => member.id_acteur_coc)).size}</TableCell><TableCell><Badge variant="outline">{team.statut}</Badge></TableCell><TableCell><Button asChild variant="ghost" size="icon"><Link href={`/dashboard/equipes-nationales/${team.id_equipe_nationale}`} aria-label="Voir"><Eye className="h-4 w-4" /></Link></Button></TableCell></TableRow>)}{!rows.length && <TableRow><TableCell colSpan={10} className="h-24 text-center text-muted-foreground">{teams.length ? "Aucune équipe nationale ne correspond aux filtres." : "Aucune équipe nationale enregistrée."}</TableCell></TableRow>}</TableBody></Table></CardContent></Card></>}</main></div>
}

function Filter({ value, set, all, options }: { value: string; set: (value: string) => void; all: string; options: NationalTeamReferences["sports"] }) { return <Select value={value} onValueChange={set}><SelectTrigger className="w-40"><SelectValue /></SelectTrigger><SelectContent><SelectItem value={all}>Tous</SelectItem>{options.map((item) => <SelectItem key={item.id} value={item.id}>{item.label}</SelectItem>)}</SelectContent></Select> }
