import "server-only"
import { appendSheetRow, deleteSheetRow, getSheetHeaders, getSheetRows, updateSheetCells } from "@/lib/google/sheets"
import { getReferentialSpreadsheetId } from "@/lib/federations/config"
import { getActeursSpreadsheetId } from "@/lib/acteurs/config"
import { ACTOR_SHEETS } from "@/lib/acteurs/sheets"
import { getActivitesSpreadsheetId } from "./config"
import { normalizeStatus } from "./format"
import { ACTIVITY_ENTITY_HEADERS, ACTIVITY_HEADERS, ACTOR_TYPES, PARTICIPANT_HEADERS, type Activity, type ActivityEntity, type ActivityParticipant, type ActivityReferences, type ActorType } from "./types"
const clean=(value:unknown)=>String(value??"").trim()
const map=(row:Record<string,string>,headers:readonly string[])=>Object.fromEntries(headers.map(key=>[key,clean(row[key])]))
const ACTIVITY_SHEET_HEADERS=["id_activite","id_type_activite","id_entite_organisatrice","nom_activite","titre_public","resume","date_debut","date_fin","pays","ville","lieu","id_statut_activite","observation"] as const
const ENTITY_SHEET_HEADERS=["id_activite_entite","id_activite","id_entite","id_role_entite_activite","observation"] as const
const PARTICIPANT_SHEET_HEADERS=["id_participation","id_activite","id_acteur_coc","id_type_acteur","id_activite_entite","observation"] as const
const ORGANIZER_ROLE_ID="REA006"
const activity=(row:Record<string,string>)=>({...map(row,ACTIVITY_HEADERS),statut:clean(row.id_statut_activite),observations:clean(row.observation),statut_normalise:normalizeStatus(row.id_statut_activite)}) as Activity
const entity=(row:Record<string,string>)=>map(row,ACTIVITY_ENTITY_HEADERS) as ActivityEntity
const participant=(row:Record<string,string>)=>map(row,PARTICIPANT_HEADERS) as ActivityParticipant
async function assertHeaders(sheetName:string,expected:readonly string[]){const headers=await getSheetHeaders({sheetName,spreadsheetId:getActivitesSpreadsheetId()});const missing=expected.filter(key=>!headers.includes(key));if(missing.length)throw new Error(`En-têtes manquants dans ${sheetName} : ${missing.join(", ")}`)}
export async function getActivities(){await assertHeaders("ACTIVITES",ACTIVITY_SHEET_HEADERS);return(await getSheetRows({sheetName:"ACTIVITES",spreadsheetId:getActivitesSpreadsheetId()})).map(activity)}
export async function getActivity(id:string){return(await getActivities()).find(x=>x.id_activite===id)}
export async function getActivityEntities(activityId?:string){await assertHeaders("ACTIVITES_ENTITES",ENTITY_SHEET_HEADERS);return(await getSheetRows({sheetName:"ACTIVITES_ENTITES",spreadsheetId:getActivitesSpreadsheetId()})).map(entity).filter(x=>!activityId||x.id_activite===activityId)}
export async function getParticipants(activityId?:string,actorId?:string){await assertHeaders("ACTIVITES_PARTICIPANTS",PARTICIPANT_SHEET_HEADERS);return(await getSheetRows({sheetName:"ACTIVITES_PARTICIPANTS",spreadsheetId:getActivitesSpreadsheetId()})).map(participant).filter(x=>(!activityId||x.id_activite===activityId)&&(!actorId||x.id_acteur_coc===actorId))}
export async function getActivityReferences():Promise<ActivityReferences>{const id=getReferentialSpreadsheetId();const[entites,types,entityRoles,actorTypes]=await Promise.all(["ENTITES","TYPES_ACTIVITE","ROLES_ENTITE_ACTIVITE","TYPES_ACTEURS"].map(sheetName=>getSheetRows({sheetName,spreadsheetId:id})));return{entites:entites.filter(r=>r.id_entite).map(r=>({id:r.id_entite,label:r.nom_officiel||r.sigle||r.id_entite,secondary:r.sigle})),types:types.filter(r=>r.id_type_activite).map(r=>({id:r.id_type_activite,label:r.nom_type_activite||r.id_type_activite})),entityRoles:entityRoles.filter(r=>r.id_role_entite_activite).map(r=>({id:r.id_role_entite_activite,label:r.nom_role_entite_activite||r.id_role_entite_activite})),actorTypes:actorTypes.filter(r=>r.id_type_acteur&&r.statut!=="INACTIF").map(r=>({id:r.id_type_acteur,label:r.nom_type_acteur||r.id_type_acteur}))}}
const nextId=(rows:Record<string,string>[],column:string,prefix:string)=>`${prefix}${String(rows.reduce((max,row)=>{const match=clean(row[column]).match(new RegExp(`^${prefix}(\\d+)$`,"i"));return match?Math.max(max,Number(match[1])):max},0)+1).padStart(4,"0")}`
const activitySheetRow=(row:Record<string,string>):Record<string,string>=>({...row,id_statut_activite:row.statut,observation:row.observations})
async function ensureOrganizerRelation(activityId:string,entityId:string){const physical=await getSheetRows({sheetName:"ACTIVITES_ENTITES",spreadsheetId:getActivitesSpreadsheetId(),bypassCache:true});const existing=physical.find(row=>row.id_activite===activityId&&row.id_entite===entityId&&row.id_role_entite_activite===ORGANIZER_ROLE_ID);if(existing)return entity(existing);const created={id_activite_entite:nextId(physical,"id_activite_entite","AEN"),id_activite:activityId,id_entite:entityId,id_role_entite_activite:ORGANIZER_ROLE_ID,observation:"Relation créée automatiquement depuis l’entité organisatrice de l’activité."} as ActivityEntity;await appendSheetRow({sheetName:"ACTIVITES_ENTITES",spreadsheetId:getActivitesSpreadsheetId(),row:created});return created}
async function validateActivity(row:Record<string,string>){if(!row.nom_activite||!row.id_type_activite||!row.id_entite_organisatrice||!row.date_debut||!row.statut)throw new Error("Nom, type, entité organisatrice, date de début et statut sont obligatoires.");if(row.date_fin&&row.date_fin<row.date_debut)throw new Error("La date de fin doit être postérieure ou égale à la date de début.");const refs=await getActivityReferences();if(!refs.types.some(x=>x.id===row.id_type_activite))throw new Error("Type d’activité inconnu.");if(!refs.entites.some(x=>x.id===row.id_entite_organisatrice))throw new Error("Entité organisatrice inconnue.")}
export async function saveActivity(input:Record<string,unknown>,id?:string){const row=map(input as Record<string,string>,ACTIVITY_HEADERS.filter(x=>x!=="id_activite")) as Record<string,string>;await validateActivity(row);const rows=await getActivities();const physical=activitySheetRow(row);if(id){if(!rows.some(x=>x.id_activite===id))throw new Error("Activité introuvable.");await updateSheetCells({sheetName:"ACTIVITES",spreadsheetId:getActivitesSpreadsheetId(),idColumn:"id_activite",idValue:id,updates:ACTIVITY_SHEET_HEADERS.filter(x=>x!=="id_activite").map(column=>({column,value:physical[column]}))});await ensureOrganizerRelation(id,row.id_entite_organisatrice);return{...row,id_activite:id}}const created:Record<string,string>={...row,id_activite:nextId(rows,"id_activite","ACT")};await appendSheetRow({sheetName:"ACTIVITES",spreadsheetId:getActivitesSpreadsheetId(),row:activitySheetRow(created)});await ensureOrganizerRelation(created.id_activite,created.id_entite_organisatrice);return created}
export async function saveActivityEntity(input:Record<string,unknown>,id?:string){const row=map(input as Record<string,string>,ACTIVITY_ENTITY_HEADERS.filter(x=>x!=="id_activite_entite")) as Record<string,string>;if(!row.id_activite||!row.id_entite||!row.id_role_entite_activite)throw new Error("Activité, entité et rôle sont obligatoires.");if(!(await getActivity(row.id_activite)))throw new Error("Activité introuvable.");const refs=await getActivityReferences();if(!refs.entites.some(x=>x.id===row.id_entite))throw new Error("Entité inconnue.");if(!refs.entityRoles.some(x=>x.id===row.id_role_entite_activite))throw new Error("Rôle d’entité inconnu.");const rows=await getActivityEntities();const existing=id?rows.find(x=>x.id_activite_entite===id):undefined;if(id&&!existing)throw new Error("Relation entité introuvable.");if(rows.some(x=>x.id_activite_entite!==id&&x.id_activite===row.id_activite&&x.id_entite===row.id_entite&&x.id_role_entite_activite===row.id_role_entite_activite))throw new Error("Cette entité possède déjà ce rôle dans l’activité.");if(id){const fixed:Record<string,string>={...row,id_activite:existing!.id_activite,id_entite:existing!.id_entite};await updateSheetCells({sheetName:"ACTIVITES_ENTITES",spreadsheetId:getActivitesSpreadsheetId(),idColumn:"id_activite_entite",idValue:id,updates:["id_role_entite_activite","observation"].map(column=>({column,value:fixed[column]}))});return{...fixed,id_activite_entite:id} as ActivityEntity}const created={...row,id_activite_entite:nextId(rows,"id_activite_entite","AEN")} as ActivityEntity;await appendSheetRow({sheetName:"ACTIVITES_ENTITES",spreadsheetId:getActivitesSpreadsheetId(),row:created});return created}
export async function deleteActivityEntity(activityId:string,id:string){const relation=(await getActivityEntities(activityId)).find(row=>row.id_activite_entite===id);if(!relation)throw new Error("Relation entité introuvable.");const activity=await getActivity(activityId);if(activity?.id_entite_organisatrice===relation.id_entite&&relation.id_role_entite_activite===ORGANIZER_ROLE_ID)throw new Error("L’entité organisatrice ne peut pas être retirée de l’activité.");if((await getParticipants(activityId)).some(row=>row.id_activite_entite===id))throw new Error("Cette entité ne peut pas être retirée car des participants lui sont rattachés.");await deleteSheetRow({sheetName:"ACTIVITES_ENTITES",spreadsheetId:getActivitesSpreadsheetId(),idColumn:"id_activite_entite",idValue:id});return relation}
const actorSheets: Record<ActorType, { sheetName: string; idKey: string }> = {
  ATHLETE: { sheetName: ACTOR_SHEETS.ATHLETE, idKey: "id_athlete_coc" },
  COACH: { sheetName: ACTOR_SHEETS.COACH, idKey: "id_coach_coc" },
  OFFICIEL: { sheetName: ACTOR_SHEETS.OFFICIEL, idKey: "id_officiel_coc" },
  MEDECIN: { sheetName: ACTOR_SHEETS.MEDECIN, idKey: "id_medecin_coc" },
  ARBITRE: { sheetName: ACTOR_SHEETS.ARBITRE, idKey: "id_arbitre_coc" },
  AUTRE: { sheetName: ACTOR_SHEETS.AUTRE, idKey: "id_autre_coc" },
}
const actorTypeAliases: Record<string, ActorType> = {
  ATHLETE: "ATHLETE", ATHLETES: "ATHLETE", COACH: "COACH", COACHS: "COACH", COACHES: "COACH", ENTRAINEUR: "COACH", ENTRAINEURS: "COACH",
  OFFICIEL: "OFFICIEL", OFFICIELS: "OFFICIEL", MEDECIN: "MEDECIN", MEDECINS: "MEDECIN",
  ARBITRE: "ARBITRE", ARBITRES: "ARBITRE",
  AUTRE: "AUTRE", AUTRES: "AUTRE",
  TYPACT001: "ATHLETE", TYPACT002: "COACH", TYPACT003: "MEDECIN", TYPACT004: "ARBITRE", TYPACT005: "OFFICIEL", TYPACT006: "AUTRE",
}
function normalizeActorType(value: string): ActorType {
  const normalized = clean(value).normalize("NFD").replace(/[\u0300-\u036f]/g, "").toUpperCase()
  const type = actorTypeAliases[normalized]
  if (!type || !ACTOR_TYPES.includes(type)) throw new Error("Type d’acteur inconnu.")
  return type
}
export async function getActors(value: string, options: { fresh?: boolean } = {}) {
  const type = normalizeActorType(value)
  const { sheetName, idKey } = actorSheets[type]
  const rows = await getSheetRows({ sheetName, spreadsheetId: getActeursSpreadsheetId(), bypassCache: options.fresh })
  const actors = rows.map((row) => ({ id: clean(row[idKey]), label: clean(row.nom_complet) || clean(row[idKey]) })).filter((actor) => actor.id)
  if (!actors.length && rows.length) {
    const headers = await getSheetHeaders({ sheetName, spreadsheetId: getActeursSpreadsheetId() })
    const missing = [idKey, "nom_complet"].filter((header) => !headers.includes(header))
    if (missing.length) throw new Error(`Mapping acteurs invalide dans ${sheetName} : ${missing.join(", ")}`)
  }
  return [...new Map(actors.map((actor) => [actor.id, actor])).values()].sort((a, b) => a.label.localeCompare(b.label, "fr", { sensitivity: "base" }))
}
export async function saveParticipant(input:Record<string,unknown>,id?:string){const row=map(input as Record<string,string>,PARTICIPANT_HEADERS.filter(x=>x!=="id_participation")) as Record<string,string>;if(!row.id_activite||!row.id_acteur_coc||!row.id_type_acteur||!row.id_activite_entite)throw new Error("Activité, type, participant et entité d’appartenance sont obligatoires.");if(!(await getActivity(row.id_activite)))throw new Error("Activité introuvable.");const typeReference=(await getActivityReferences()).actorTypes.find(type=>type.id===row.id_type_acteur);if(!typeReference)throw new Error("Type d’acteur inconnu.");if(!(await getActors(typeReference.label)).some(x=>x.id===row.id_acteur_coc))throw new Error("Participant introuvable ou type incohérent.");const relation=(await getActivityEntities(row.id_activite)).find(item=>item.id_activite_entite===row.id_activite_entite);if(!relation)throw new Error("L’entité sélectionnée n’est pas rattachée à cette activité.");const rows=await getParticipants();const existing=id?rows.find(x=>x.id_participation===id):undefined;if(id&&!existing)throw new Error("Participation introuvable.");const fixed=id?{...row,id_activite:existing!.id_activite}:row;if(rows.some(x=>x.id_participation!==id&&x.id_activite===fixed.id_activite&&x.id_acteur_coc===fixed.id_acteur_coc))throw new Error("Ce participant est déjà enregistré dans cette activité.");if(id){await updateSheetCells({sheetName:"ACTIVITES_PARTICIPANTS",spreadsheetId:getActivitesSpreadsheetId(),idColumn:"id_participation",idValue:id,updates:["id_acteur_coc","id_type_acteur","id_activite_entite","observation"].map(column=>({column,value:fixed[column]}))});return{...fixed,id_participation:id} as ActivityParticipant}const created={...fixed,id_participation:nextId(rows,"id_participation","PAR")} as ActivityParticipant;await appendSheetRow({sheetName:"ACTIVITES_PARTICIPANTS",spreadsheetId:getActivitesSpreadsheetId(),row:created});return created}
