import { NextResponse } from "next/server"
import { getSession } from "@/lib/auth"
import { assignAuthorization, changeAuthorization } from "@/lib/users/administration-workflows"
import { createGoogleUsersSheetsAdapter } from "@/lib/users/google-adapter"
import { UsersRepository } from "@/lib/users/repository"
type Context = { params: Promise<{ id: string }> }
async function context(request: Request, route: Context) { const adapter = createGoogleUsersSheetsAdapter(), id = (await route.params).id, body = await request.json(), repository = new UsersRepository(adapter), target = await repository.requireUserById(id), requestId = String(body.requestId ?? "").trim(); if (!requestId) throw new Error("request_id obligatoire."); return { adapter, id, body, repository, requestId, target } }
export async function POST(request: Request, route: Context) { const session = await getSession(); if (!session?.estSuperAdmin) return NextResponse.json({ error: "Accès refusé." }, { status: 403 }); try { const value = await context(request, route), authorization = await assignAuthorization({ adapter: value.adapter, actorId: session.idUser, requestId: value.requestId, target: value.target, block: value.body.block, dateDebut: value.body.dateDebut, dateFin: value.body.dateFin || null }); return NextResponse.json({ ok: true, authorization }) } catch (error) { return NextResponse.json({ error: error instanceof Error ? error.message : "Attribution impossible." }, { status: 400 }) } }
export async function PATCH(request: Request, route: Context) { const session = await getSession(); if (!session?.estSuperAdmin) return NextResponse.json({ error: "Accès refusé." }, { status: 403 }); try { const value = await context(request, route), before = (await value.repository.getAuthorizationsForUser(value.id)).find((item) => item.idUserAutorisation === value.body.id); if (!before) return NextResponse.json({ error: "Autorisation introuvable." }, { status: 404 }); const after = { ...before, statut: value.body.statut ?? before.statut, dateDebut: value.body.dateDebut ?? before.dateDebut, dateFin: value.body.dateFin === undefined ? before.dateFin : value.body.dateFin || null }; return NextResponse.json({ ok: true, authorization: await changeAuthorization({ adapter: value.adapter, actorId: session.idUser, requestId: value.requestId, target: value.target, before, after }) }) } catch (error) { return NextResponse.json({ error: error instanceof Error ? error.message : "Modification impossible." }, { status: 400 }) } }
export async function DELETE(request: Request, route: Context) { const session = await getSession(); if (!session?.estSuperAdmin) return NextResponse.json({ error: "Accès refusé." }, { status: 403 }); try { const value = await context(request, route), before = (await value.repository.getAuthorizationsForUser(value.id)).find((item) => item.idUserAutorisation === value.body.id); if (!before) return NextResponse.json({ error: "Autorisation introuvable." }, { status: 404 }); const kinshasaDate = new Intl.DateTimeFormat("en-CA", { timeZone: "Africa/Kinshasa", year: "numeric", month: "2-digit", day: "2-digit" }).format(new Date()), after = { ...before, statut: "INACTIF" as const, dateFin: before.dateFin ?? (value.body.dateFin || kinshasaDate) }; return NextResponse.json({ ok: true, authorization: await changeAuthorization({ adapter: value.adapter, actorId: session.idUser, requestId: value.requestId, target: value.target, before, after }) }) } catch (error) { return NextResponse.json({ error: error instanceof Error ? error.message : "Retrait impossible." }, { status: 400 }) } }
