export const AUDIT_ACTIONS = {
  LOGIN: "CONNEXION",
  ACCOUNT_ACTIVATION: "ACTIVATION_COMPTE",
  PASSWORD_CHANGE: "CHANGEMENT_MOT_DE_PASSE",
  ACCESS_RESET: "REINITIALISATION_ACCES",
  USER_CREATE: "CREATION_UTILISATEUR",
  USER_UPDATE: "MODIFICATION_UTILISATEUR",
  SESSION_REVOKE: "REVOCATION_SESSIONS",
  AUTHORIZATION_ASSIGN: "ATTRIBUTION_AUTORISATION",
  AUTHORIZATION_UPDATE: "MODIFICATION_AUTORISATION",
  SPORT_CREATE: "CREATION_OBJET_SPORTIF",
  SPORT_UPDATE: "MODIFICATION_OBJET_SPORTIF",
} as const
