"use client"
import Link from "next/link"
import {useMemo,useState} from "react"
import {useRouter} from "next/navigation"
import {ChevronLeft,ChevronRight,Eye,Plus,Search} from "lucide-react"
import {toast} from "sonner"
import {CompetitionForm,emptyCompetitionForm} from "@/components/dashboard/competition-form"
import {Header} from "@/components/dashboard/header"
import {Badge} from "@/components/ui/badge"
import {Button} from "@/components/ui/button"
import {Card,CardContent} from "@/components/ui/card"
import {Input} from "@/components/ui/input"
import {Select,SelectContent,SelectItem,SelectTrigger,SelectValue} from "@/components/ui/select"
import {Sheet,SheetContent,SheetDescription,SheetHeader,SheetTitle} from "@/components/ui/sheet"
import {Table,TableBody,TableCell,TableHead,TableHeader,TableRow} from "@/components/ui/table"
import {Tooltip,TooltipContent,TooltipProvider,TooltipTrigger} from "@/components/ui/tooltip"
import {competitionStatusLabels,formatCompetitionPeriod} from "@/lib/competitions/format"
import {competitionFormError} from "@/lib/competitions/form-validation"
import type {Competition,CompetitionOption} from "@/lib/competitions/types"
const shown=(value?:string)=>value||"Non renseigné"
export default function CompetitionsClient({competitions,types,levels,statuses,delegationCounts,canEdit,initialCreate=false,loadError}:{competitions:Competition[];types:CompetitionOption[];levels:CompetitionOption[];statuses:CompetitionOption[];delegationCounts:Record<string,number>;canEdit:boolean;initialCreate?:boolean;loadError?:string}){
 const router=useRouter()
 const[query,setQuery]=useState(""),[status,setStatus]=useState("tous"),[periodStart,setPeriodStart]=useState(""),[periodEnd,setPeriodEnd]=useState(""),[page,setPage]=useState(1),[pageSize,setPageSize]=useState(10)
 const[createOpen,setCreateOpen]=useState(initialCreate),[form,setForm]=useState(emptyCompetitionForm),[saving,setSaving]=useState(false)
 const rows=useMemo(()=>{const needle=query.trim().toLocaleLowerCase("fr");return competitions.filter((item)=>{const identity=[item.id_competition,item.nom_competition,item.edition].join(" ").toLocaleLowerCase("fr"),overlaps=(!periodStart||!item.date_fin||item.date_fin>=periodStart)&&(!periodEnd||!item.date_debut||item.date_debut<=periodEnd);return(!needle||identity.includes(needle))&&(status==="tous"||item.statut_normalise===status)&&overlaps}).sort((a,b)=>a.nom_competition.localeCompare(b.nom_competition,"fr",{sensitivity:"base"}))},[competitions,periodEnd,periodStart,query,status])
 const pageCount=Math.max(1,Math.ceil(rows.length/pageSize)),currentPage=Math.min(page,pageCount),visible=rows.slice((currentPage-1)*pageSize,currentPage*pageSize),filter=(action:()=>void)=>{action();setPage(1)}
 const detail=(item:Competition)=><TooltipProvider><Tooltip><TooltipTrigger asChild><Button asChild variant="ghost" size="icon"><Link href={`/dashboard/competitions/${encodeURIComponent(item.id_competition)}`} aria-label={`Voir les détails de ${item.nom_competition}`}><Eye className="h-4 w-4"/></Link></Button></TooltipTrigger><TooltipContent>Voir les détails</TooltipContent></Tooltip></TooltipProvider>
 async function createCompetition(){const validationError=competitionFormError(form,types,levels,statuses);if(validationError){toast.error(validationError);return}setSaving(true);try{const response=await fetch("/api/competitions",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({row:form})}),result=await response.json();if(!response.ok)throw new Error(result.message||result.error||`Enregistrement impossible (${response.status}).`);toast.success("Compétition créée.");setCreateOpen(false);router.push(`/dashboard/competitions/${result.row.id_competition}`)}catch(error){toast.error(error instanceof Error?error.message:String(error))}finally{setSaving(false)}}
 return <div className="min-h-screen min-w-0 overflow-x-hidden"><Header title="Compétitions" subtitle="Éditions concrètes des événements sportifs suivis par le COC"/><main className="min-w-0 space-y-5 p-4 md:p-6">
  <div className="flex justify-end">{canEdit&&<Button onClick={()=>{setForm(emptyCompetitionForm);setCreateOpen(true)}}><Plus className="mr-2 h-4 w-4"/>Nouvelle compétition</Button>}</div>
  {loadError&&<p role="alert" className="rounded-lg border border-destructive/30 p-4 text-destructive">{loadError} La page reste disponible.</p>}
  <div className="grid min-w-0 gap-3 md:grid-cols-2 xl:grid-cols-[minmax(16rem,1fr)_12rem_11rem_11rem]"><div className="relative md:col-span-2 xl:col-span-1"><Search className="absolute left-3 top-3 h-4 w-4 text-muted-foreground"/><Input className="pl-9" aria-label="Rechercher une compétition" placeholder="Identifiant, nom ou édition…" value={query} onChange={(e)=>filter(()=>setQuery(e.target.value))}/></div><Select value={status} onValueChange={(v)=>filter(()=>setStatus(v))}><SelectTrigger aria-label="Filtrer par statut"><SelectValue/></SelectTrigger><SelectContent><SelectItem value="tous">Tous les statuts</SelectItem>{Object.entries(competitionStatusLabels).map(([id,label])=><SelectItem key={id} value={id}>{label}</SelectItem>)}</SelectContent></Select><Input type="date" aria-label="Période à partir du" value={periodStart} onChange={(e)=>filter(()=>setPeriodStart(e.target.value))}/><Input type="date" aria-label="Période jusqu’au" min={periodStart||undefined} value={periodEnd} onChange={(e)=>filter(()=>setPeriodEnd(e.target.value))}/></div>
  <Card className="min-w-0 overflow-hidden"><CardContent className="p-0"><div className="hidden lg:block"><Table><TableHeader><TableRow><TableHead>Période</TableHead><TableHead>Nom de la compétition</TableHead><TableHead>Édition</TableHead><TableHead className="text-right">Total délégation</TableHead><TableHead>Statut</TableHead><TableHead className="w-14"/></TableRow></TableHeader><TableBody>{visible.map((item)=><TableRow key={item.id_competition}><TableCell>{formatCompetitionPeriod(item.date_debut,item.date_fin)}</TableCell><TableCell className="max-w-80 whitespace-normal font-medium">{shown(item.nom_competition)}</TableCell><TableCell>{shown(item.edition)}</TableCell><TableCell className="text-right tabular-nums">{delegationCounts[item.id_competition]||0}</TableCell><TableCell><Badge variant="outline">{shown(competitionStatusLabels[item.statut_normalise])}</Badge></TableCell><TableCell>{detail(item)}</TableCell></TableRow>)}{!visible.length&&<TableRow><TableCell colSpan={6} className="h-24 text-center text-muted-foreground">{competitions.length?"Aucune compétition ne correspond aux critères.":"Aucune compétition enregistrée."}</TableCell></TableRow>}</TableBody></Table></div>
   <div className="grid min-w-0 gap-3 p-3 sm:grid-cols-2 lg:hidden">{visible.map((item)=><article key={item.id_competition} className="min-w-0 rounded-lg border p-4"><div className="flex items-start justify-between gap-3"><div className="min-w-0"><p className="text-xs text-muted-foreground">{formatCompetitionPeriod(item.date_debut,item.date_fin)}</p><h2 className="break-words font-semibold">{shown(item.nom_competition)}</h2></div>{detail(item)}</div><div className="mt-3 space-y-2 text-sm"><p><span className="text-muted-foreground">Édition : </span>{shown(item.edition)}</p><p><span className="text-muted-foreground">Total délégation : </span><span className="tabular-nums">{delegationCounts[item.id_competition]||0}</span></p><Badge variant="outline">{shown(competitionStatusLabels[item.statut_normalise])}</Badge></div></article>)}{!visible.length&&<p className="py-10 text-center text-sm text-muted-foreground sm:col-span-2">{competitions.length?"Aucune compétition ne correspond aux critères.":"Aucune compétition enregistrée."}</p>}</div>
  </CardContent></Card>
  <div className="flex flex-col gap-3 sm:flex-row sm:items-center sm:justify-between"><p className="text-sm text-muted-foreground">{rows.length} résultat(s) · page {currentPage} sur {pageCount}</p><div className="flex items-center gap-2"><Select value={String(pageSize)} onValueChange={(v)=>filter(()=>setPageSize(Number(v)))}><SelectTrigger className="w-24" aria-label="Résultats par page"><SelectValue/></SelectTrigger><SelectContent>{[10, 20, 50].map((size)=><SelectItem key={size} value={String(size)}>{size}</SelectItem>)}</SelectContent></Select><Button variant="outline" size="icon" disabled={currentPage<=1} onClick={()=>setPage(currentPage-1)} aria-label="Page précédente"><ChevronLeft className="h-4 w-4"/></Button><Button variant="outline" size="icon" disabled={currentPage>=pageCount} onClick={()=>setPage(currentPage+1)} aria-label="Page suivante"><ChevronRight className="h-4 w-4"/></Button></div></div>
 </main><Sheet open={createOpen} onOpenChange={setCreateOpen}><SheetContent className="w-full overflow-y-auto sm:max-w-2xl"><SheetHeader><SheetTitle>Nouvelle compétition</SheetTitle><SheetDescription>Enregistrer une édition concrète d’une compétition.</SheetDescription></SheetHeader><div className="px-4"><CompetitionForm value={form} onChange={setForm} types={types} levels={levels} statuses={statuses} saving={saving} onSubmit={createCompetition} onCancel={()=>setCreateOpen(false)}/></div></SheetContent></Sheet></div>
}
