"use client"
import Link from "next/link"
import { ArrowLeft, Eye, Pencil, Plus } from "lucide-react"
import { useState } from "react"
import { useRouter } from "next/navigation"
import { toast } from "sonner"
import { Header } from "@/components/dashboard/header"
import { NationalTeamForm, nationalTeamToForm } from "@/components/dashboard/national-team-form"
import { ActorSearchSelect } from "@/components/dashboard/actor-search-select"
import { Badge } from "@/components/ui/badge"
import { Button } from "@/components/ui/button"
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card"
import { Input } from "@/components/ui/input"
import { Label } from "@/components/ui/label"
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select"
import { Sheet, SheetContent, SheetDescription, SheetHeader, SheetTitle } from "@/components/ui/sheet"
import { Table, TableBody, TableCell, TableHead, TableHeader, TableRow } from "@/components/ui/table"
import { Tabs, TabsContent, TabsList, TabsTrigger } from "@/components/ui/tabs"
import { Textarea } from "@/components/ui/textarea"
import { formatCompetitionPeriod, formatDateFr } from "@/lib/competitions/format"
import { isActiveNationalTeamMember, type NationalTeam, type NationalTeamMember, type NationalTeamReferences } from "@/lib/equipes-nationales/types"
import type { Competition, TeamParticipation } from "@/lib/competitions/types"
import type { DocumentRecord } from "@/lib/documents/types"

const emptyMember = { id_acteur_coc: "", id_type_acteur: "ATHLETE", role_equipe: "ATHLETE", date_debut: "", date_fin: "", statut: "ACTIF", observations: "" }
const actorTypes: Record<string, string> = { ATHLETE: "Athlète", COACH: "Coach", MEDECIN: "Médecin", OFFICIEL: "Officiel", ARBITRE: "Arbitre" }
const formatSize = (value: string) => { const bytes = Number(value); return !bytes ? "—" : bytes >= 1048576 ? `${(bytes / 1048576).toFixed(1)} Mo` : `${Math.ceil(bytes / 1024)} Ko` }

export default function Client({ team: initial, references, members: initialMembers, actorLabels, membersError, competitions, documents, canEdit }: { team: NationalTeam; references: NationalTeamReferences; members: NationalTeamMember[]; actorLabels: Record<string, string>; membersError: boolean; competitions?: [Competition[], TeamParticipation[]]; documents?: DocumentRecord[]; canEdit: boolean }) {
  const router = useRouter(), [team, setTeam] = useState(initial), [members, setMembers] = useState(initialMembers), [editOpen, setEditOpen] = useState(false), [memberOpen, setMemberOpen] = useState(false), [memberId, setMemberId] = useState(""), [form, setForm] = useState(nationalTeamToForm(initial)), [memberForm, setMemberForm] = useState(emptyMember), [actors, setActors] = useState<{ id: string; label: string }[]>([]), [saving, setSaving] = useState(false), [memberFilter, setMemberFilter] = useState("ACTIFS")
  const label = (items: NationalTeamReferences["sports"], id: string) => items.find((item) => item.id === id)?.label || id || "—"
  const visibleMembers = [...members].filter((member) => memberFilter === "TOUS" || (memberFilter === "ACTIFS") === isActiveNationalTeamMember(member)).sort((a, b) => b.date_debut.localeCompare(a.date_debut))
  const competitionRows = competitions ? competitions[1].filter((row) => row.id_equipe_nationale === team.id_equipe_nationale).map((relation) => ({ relation, competition: competitions[0].find((item) => item.id_competition === relation.id_competition) })).filter((row) => row.competition) : []

  async function loadActors(type: string) { setMemberForm((current) => ({ ...current, id_type_acteur: type, id_acteur_coc: "" })); try { const response = await fetch(`/api/equipes-nationales/acteurs?type=${type}`), result = await response.json(); if (!response.ok) throw new Error(result.error); setActors(result.rows) } catch (error) { toast.error(error instanceof Error ? error.message : String(error)) } }
  async function saveTeam() { setSaving(true); try { const response = await fetch("/api/equipes-nationales", { method: "PATCH", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ id: team.id_equipe_nationale, row: form }) }), result = await response.json(); if (!response.ok) throw new Error(result.error); setTeam(result.row); setEditOpen(false); toast.success("Équipe nationale modifiée."); router.refresh() } catch (error) { toast.error(error instanceof Error ? error.message : String(error)) } finally { setSaving(false) } }
  function addMember() { setMemberId(""); setMemberForm(emptyMember); setActors([]); setMemberOpen(true); loadActors("ATHLETE") }
  function editMember(member: NationalTeamMember) { setMemberId(member.id_membre_equipe_nationale); setMemberForm({ id_acteur_coc: member.id_acteur_coc, id_type_acteur: member.id_type_acteur, role_equipe: member.role_equipe, date_debut: member.date_debut, date_fin: member.date_fin, statut: member.statut, observations: member.observations }); setActors([{ id: member.id_acteur_coc, label: actorLabels[`${member.id_type_acteur}:${member.id_acteur_coc}`] || member.id_acteur_coc }]); setMemberOpen(true) }
  async function saveMember() { setSaving(true); try { const response = await fetch(`/api/equipes-nationales/${team.id_equipe_nationale}/membres`, { method: memberId ? "PATCH" : "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ id: memberId, row: memberForm }) }), result = await response.json(); if (!response.ok) throw new Error(result.error); setMembers((current) => memberId ? current.map((member) => member.id_membre_equipe_nationale === memberId ? result.row : member) : [...current, result.row]); setMemberOpen(false); toast.success(memberId ? "Membre modifié." : "Membre ajouté."); router.refresh() } catch (error) { toast.error(error instanceof Error ? error.message : String(error)) } finally { setSaving(false) } }
  function closeMembership() { setMemberForm((current) => ({ ...current, statut: "INACTIF", date_fin: current.date_fin || new Date().toISOString().slice(0, 10) })) }

  return <div><Header title={team.nom_equipe_nationale} subtitle={`${team.id_equipe_nationale} · ${team.statut}`} /><main className="space-y-5 p-4 md:p-6"><Button asChild variant="ghost"><Link href="/dashboard/equipes-nationales"><ArrowLeft className="mr-2 h-4 w-4" />Retour</Link></Button><Tabs defaultValue="general"><TabsList className="grid w-full max-w-2xl grid-cols-4"><TabsTrigger value="general">Général</TabsTrigger><TabsTrigger value="members">Membres</TabsTrigger><TabsTrigger value="competitions">Compétitions</TabsTrigger><TabsTrigger value="documents">Documents</TabsTrigger></TabsList>
    <TabsContent value="general"><Card><CardHeader className="flex flex-row items-center justify-between"><CardTitle>Informations générales</CardTitle>{canEdit && <Button variant="outline" onClick={() => { setForm(nationalTeamToForm(team)); setEditOpen(true) }}><Pencil className="mr-2 h-4 w-4" />Modifier</Button>}</CardHeader><CardContent className="grid gap-5 sm:grid-cols-2 lg:grid-cols-3">{[["ID", team.id_equipe_nationale], ["Fédération", label(references.federations, team.id_federation)], ["Sport", label(references.sports, team.id_sport)], ["Discipline", label(references.disciplines, team.id_discipline)], ["Catégorie", label(references.ageCategories, team.id_categorie_age)], ["Sexe", label(references.sexes, team.id_sexe)], ["Statut", team.statut], ["Date de début", formatDateFr(team.date_debut)], ["Date de fin", team.date_fin ? formatDateFr(team.date_fin) : "En cours"], ["Observations", team.observations]].map(([title, value]) => <div key={title}><p className="text-sm text-muted-foreground">{title}</p><p className="font-medium">{value || "—"}</p></div>)}</CardContent></Card></TabsContent>
    <TabsContent value="members"><Card><CardHeader className="flex flex-row flex-wrap items-center justify-between gap-3"><CardTitle>Membres</CardTitle><div className="flex gap-2"><Select value={memberFilter} onValueChange={setMemberFilter}><SelectTrigger className="w-36"><SelectValue /></SelectTrigger><SelectContent><SelectItem value="ACTIFS">Actifs</SelectItem><SelectItem value="HISTORIQUE">Historique</SelectItem><SelectItem value="TOUS">Tous</SelectItem></SelectContent></Select>{canEdit && <Button onClick={addMember}><Plus className="mr-2 h-4 w-4" />Ajouter</Button>}</div></CardHeader><CardContent className="overflow-x-auto p-0">{membersError ? <p className="p-6 text-destructive">Impossible de charger les membres.</p> : <Table><TableHeader><TableRow><TableHead>Acteur</TableHead><TableHead>Type</TableHead><TableHead>Rôle</TableHead><TableHead>Début</TableHead><TableHead>Fin</TableHead><TableHead>Statut</TableHead><TableHead /></TableRow></TableHeader><TableBody>{visibleMembers.map((member) => <TableRow key={member.id_membre_equipe_nationale}><TableCell><p className="font-medium">{actorLabels[`${member.id_type_acteur}:${member.id_acteur_coc}`] || member.id_acteur_coc}</p><p className="font-mono text-xs text-muted-foreground">{member.id_acteur_coc}</p></TableCell><TableCell>{actorTypes[member.id_type_acteur] || member.id_type_acteur}</TableCell><TableCell>{label(references.roles, member.role_equipe)}</TableCell><TableCell>{formatDateFr(member.date_debut)}</TableCell><TableCell>{formatDateFr(member.date_fin)}</TableCell><TableCell><Badge variant="outline">{member.statut}</Badge></TableCell><TableCell>{canEdit && <Button variant="ghost" size="sm" onClick={() => editMember(member)}>Modifier</Button>}</TableCell></TableRow>)}{!visibleMembers.length && <TableRow><TableCell colSpan={7} className="h-24 text-center text-muted-foreground">Aucun membre dans cette vue.</TableCell></TableRow>}</TableBody></Table>}</CardContent></Card></TabsContent>
    <TabsContent value="competitions"><Card><CardHeader><CardTitle>Compétitions</CardTitle></CardHeader><CardContent className="overflow-x-auto p-0"><Table><TableHeader><TableRow><TableHead>Compétition</TableHead><TableHead>Période</TableHead><TableHead>Statut participation</TableHead><TableHead /></TableRow></TableHeader><TableBody>{competitionRows.map((row) => <TableRow key={row.relation.id_participation_equipe}><TableCell>{row.competition!.nom_competition}</TableCell><TableCell>{formatCompetitionPeriod(row.competition!.date_debut, row.competition!.date_fin)}</TableCell><TableCell>{row.relation.statut_participation}</TableCell><TableCell><Button asChild variant="ghost" size="icon"><Link href={`/dashboard/competitions/${row.competition!.id_competition}`} aria-label="Voir"><Eye className="h-4 w-4" /></Link></Button></TableCell></TableRow>)}{!competitionRows.length && <TableRow><TableCell colSpan={4} className="h-24 text-center text-muted-foreground">Aucune compétition liée.</TableCell></TableRow>}</TableBody></Table></CardContent></Card></TabsContent>
    <TabsContent value="documents"><Card><CardHeader><CardTitle>Documents</CardTitle></CardHeader><CardContent className="overflow-x-auto p-0">{documents === undefined ? <p className="p-6 text-muted-foreground">Documents accessibles au rôle COC.</p> : <Table><TableHeader><TableRow><TableHead>Document</TableHead><TableHead>Type</TableHead><TableHead>Taille</TableHead><TableHead>Fichier</TableHead><TableHead /></TableRow></TableHeader><TableBody>{documents.map((document) => <TableRow key={document.id_document}><TableCell className="font-medium">{document.nom_document}</TableCell><TableCell>{document.id_type_document || "—"}</TableCell><TableCell>{formatSize(document.taille)}</TableCell><TableCell><Badge variant={document.drive_document_id ? "secondary" : "outline"}>{document.drive_document_id ? "Disponible" : "Non disponible"}</Badge></TableCell><TableCell><Button asChild variant="ghost" size="icon"><Link href={`/dashboard/documents/${document.id_document}`} aria-label="Voir"><Eye className="h-4 w-4" /></Link></Button></TableCell></TableRow>)}{!documents.length && <TableRow><TableCell colSpan={5} className="h-24 text-center text-muted-foreground">Aucun document lié.</TableCell></TableRow>}</TableBody></Table>}</CardContent></Card></TabsContent>
  </Tabs>
  <Sheet open={editOpen} onOpenChange={setEditOpen}><SheetContent className="w-full overflow-y-auto sm:max-w-2xl"><SheetHeader><SheetTitle>Modifier l’équipe nationale</SheetTitle><SheetDescription>L’identifiant, la fédération et le sport restent immuables.</SheetDescription></SheetHeader><div className="px-4"><NationalTeamForm value={form} onChange={setForm} references={references} saving={saving} onSubmit={saveTeam} onCancel={() => setEditOpen(false)} editing /></div></SheetContent></Sheet>
  <Sheet open={memberOpen} onOpenChange={setMemberOpen}><SheetContent className="w-full overflow-y-auto sm:max-w-lg"><SheetHeader><SheetTitle>{memberId ? "Modifier le membre" : "Ajouter un membre"}</SheetTitle><SheetDescription>Cette appartenance ne constitue pas une sélection pour une compétition.</SheetDescription></SheetHeader><div className="space-y-4 px-4"><div className="space-y-2"><Label>Type d’acteur *</Label><Select disabled={Boolean(memberId)} value={memberForm.id_type_acteur} onValueChange={loadActors}><SelectTrigger><SelectValue /></SelectTrigger><SelectContent>{Object.entries(actorTypes).map(([id, title]) => <SelectItem key={id} value={id}>{title}</SelectItem>)}</SelectContent></Select></div><div className="space-y-2"><Label>Acteur *</Label><ActorSearchSelect value={memberForm.id_acteur_coc} onValueChange={(value) => setMemberForm({ ...memberForm, id_acteur_coc: value })} options={actors} disabled={Boolean(memberId)} placeholder="Rechercher un acteur" /></div><div className="space-y-2"><Label>Rôle *</Label><Select value={memberForm.role_equipe} onValueChange={(value) => setMemberForm({ ...memberForm, role_equipe: value })}><SelectTrigger><SelectValue /></SelectTrigger><SelectContent>{references.roles.map((role) => <SelectItem key={role.id} value={role.id}>{role.label}</SelectItem>)}</SelectContent></Select></div><div className="space-y-2"><Label>Date de début *</Label><Input type="date" value={memberForm.date_debut} onChange={(event) => setMemberForm({ ...memberForm, date_debut: event.target.value })} /></div><div className="space-y-2"><Label>Date de fin</Label><Input type="date" value={memberForm.date_fin} onChange={(event) => setMemberForm({ ...memberForm, date_fin: event.target.value })} /></div><div className="space-y-2"><Label>Statut *</Label><Select value={memberForm.statut} onValueChange={(value) => setMemberForm({ ...memberForm, statut: value })}><SelectTrigger><SelectValue /></SelectTrigger><SelectContent><SelectItem value="ACTIF">Actif</SelectItem><SelectItem value="INACTIF">Inactif</SelectItem></SelectContent></Select></div><div className="space-y-2"><Label>Observations</Label><Textarea value={memberForm.observations} onChange={(event) => setMemberForm({ ...memberForm, observations: event.target.value })} /></div><div className="flex flex-wrap justify-end gap-2">{memberId && memberForm.statut === "ACTIF" && <Button variant="outline" onClick={closeMembership}>Clôturer</Button>}<Button variant="outline" onClick={() => setMemberOpen(false)}>Annuler</Button><Button disabled={saving} onClick={saveMember}>Enregistrer</Button></div></div></SheetContent></Sheet>
  </main></div>
}
