import assert from "node:assert/strict"
import test from "node:test"
import {readFileSync} from "node:fs"
import {validateCompetitionResultInput} from "../../lib/competitions/validation.ts"

const base={id_engagement_campagne:"ENG1",date_resultat:"2028-07-10",id_federation_source:"FED1",date_transmission:"2028-07-11",id_statut_validation_resultat:"TRANSMIS"}
test("accepte victoire, nul, défaite et qualification sans calcul",()=>{for(const id of ["SYN_VICTOIRE","SYN_NUL","SYN_DEFAITE","SYN_QUALIFIE"])assert.equal(validateCompetitionResultInput({...base,id_resultat_synthetique:id}).id_resultat_synthetique,id)})
test("accepte un score ou une mesure avec unité",()=>{assert.equal(validateCompetitionResultInput({...base,valeur_rdc:"82",valeur_adversaire:"76",adversaire:"Angola",id_unite_mesure:"UNIT_POINT"}).valeur_rdc,"82");assert.equal(validateCompetitionResultInput({...base,valeur_rdc:"10.12",id_unite_mesure:"UNIT_SECONDE"}).id_unite_mesure,"UNIT_SECONDE")})
test("accepte un rang sans inventer une unité",()=>{const row=validateCompetitionResultInput({...base,valeur_rdc:"1"});assert.equal(row.valeur_rdc,"1");assert.equal(row.id_unite_mesure,"")})
test("accepte une décision sans score et refuse un résultat vide",()=>{assert.equal(validateCompetitionResultInput({...base,id_decision_resultat:"DEC_FORFAIT"}).id_decision_resultat,"DEC_FORFAIT");assert.throws(()=>validateCompetitionResultInput(base),/synthèse/i)})
test("exige les preuves de validation et d’homologation",()=>{assert.throws(()=>validateCompetitionResultInput({...base,id_resultat_synthetique:"SYN_VICTOIRE",id_statut_validation_resultat:"HOMOLOGUE"}),/date de validation/i);assert.throws(()=>validateCompetitionResultInput({...base,id_resultat_synthetique:"SYN_VICTOIRE",id_statut_validation_resultat:"HOMOLOGUE",date_validation:"2028-07-12"}),/validateur COC/i)})
test("la correction est versionnée et ne modifie pas silencieusement le résultat",()=>{const source=readFileSync("lib/competitions/data.ts","utf8");assert.match(source,/id_resultat_precedent:current\.id_resultat/);assert.match(source,/numero_version:String\(Number\(current\.numero_version\)\+1\)/);assert.match(source,/id_statut_validation_resultat",value:"CORRIGE"/)})
test("l’interface expose l’historique sans segments ni classement",()=>{const source=readFileSync("components/dashboard/competition-results.tsx","utf8");assert.match(source,/Correction versionnée/);assert.match(source,/Aucun classement n’est calculé/);assert.doesNotMatch(source,/RESULTATS_SEGMENTS|classement automatique|overflow-x-auto/)})
test("l’API résultats contrôle les droits serveur",()=>{const source=readFileSync("app/api/competitions/[id]/resultats/route.ts","utf8");assert.match(source,/canAccess\("AUT-SPT","READ"\)/);assert.match(source,/runSportMutation|canAccess\("AUT-SPT","WRITE"\)/);assert.match(source,/getSession\(\)/)})
