import assert from "node:assert/strict"
import test from "node:test"
import {readFileSync} from "node:fs"
import {isPerformanceReferenceCompatible,validateIndividualPerformanceInput} from "../../lib/competitions/validation.ts"

const base={id_resultat:"RES1",id_participation_athlete:"PAT1",id_type_resultat:"TR_TEMPS"}
test("accepte temps, distance, hauteur, poids et note",()=>{for(const [type,unit] of [["TR_TEMPS","UNIT_SECONDE"],["TR_DISTANCE","UNIT_METRE"],["TR_HAUTEUR","UNIT_METRE"],["TR_POIDS","UNIT_KILOGRAMME"],["TR_NOTE","UNIT_NOTE"]]){const row=validateIndividualPerformanceInput({...base,id_type_resultat:type,valeur:"10.25",id_unite_mesure:unit});assert.equal(row.id_type_resultat,type)}})
test("distingue le rang d’épreuve d’un classement général",()=>{const row=validateIndividualPerformanceInput({...base,id_type_resultat:"TR_RANG",rang:"1"});assert.equal(row.rang,"1");assert.throws(()=>validateIndividualPerformanceInput({...base,rang:"0"}),/rang/i)})
test("accepte record, meilleure performance et distinction sans les homologuer",()=>{const row=validateIndividualPerformanceInput({...base,valeur:"9.90",id_unite_mesure:"UNIT_SECONDE",est_record:"OUI",est_meilleure_performance:"OUI",id_distinction:"DIST_OR"});assert.equal(row.est_record,"OUI");assert.equal(row.id_distinction,"DIST_OR")})
test("refuse une performance dépourvue de valeur, rang et distinction",()=>{assert.throws(()=>validateIndividualPerformanceInput(base),/valeur, un rang ou une distinction/i)})
test("filtre types et distinctions selon le contexte sportif",()=>{const context={federationId:"FED1",sportId:"ATH",disciplineId:"100M"};assert.equal(isPerformanceReferenceCompatible({sportId:"ATH"},context),true);assert.equal(isPerformanceReferenceCompatible({disciplineId:"MARATHON"},context),false);assert.equal(isPerformanceReferenceCompatible({},context),true)})
test("la donnée exige un participant effectif et une unité compatible",()=>{const source=readFileSync("lib/competitions/data.ts","utf8");assert.match(source,/id_statut_participation==="PARTICIPANT"/);assert.match(source,/Un participant effectif du même engagement est obligatoire/);assert.match(source,/L’unité ne correspond pas au type de résultat/)})
test("l’interface montre la provenance et ne calcule aucun classement",()=>{const source=readFileSync("components/dashboard/individual-performances.tsx","utf8");assert.match(source,/Source :/);assert.match(source,/Aucun classement général n’est calculé/);assert.doesNotMatch(source,/sort\(.*rang|classementGeneral|homologuer/i);assert.doesNotMatch(source,/overflow-x-auto/)})
test("l’API performances contrôle les droits serveur",()=>{const source=readFileSync("app/api/competitions/[id]/performances/route.ts","utf8");assert.match(source,/canAccess\("AUT-SPT","READ"\)/);assert.match(source,/runSportMutation|canAccess\("AUT-SPT","WRITE"\)/)})
